const characters = {
	re_xushu: ["male", "shu", 4, ["zhuhai", "qianxin"]],
	re_lidian: ["male", "wei", 3, ["xunxun", "xinwangxi"], ["die:lidian"]],
	re_zhongyao: ["male", "wei", 3, ["rehuomo", "zuoding"], ["clan:颍川钟氏"]],
	xin_zhangliang: ["male", "qun", 4, ["rejijun", "refangtong"]],
	re_simalang: ["male", "wei", 3, ["requji", "rejunbing"], ["name:司马|朗"]],
	re_zhugedan: ["male", "wei", 4, ["regongao", "rejuyi"], ["name:诸葛|诞"]],
	re_caorui: ["male", "wei", 3, ["huituo", "remingjian", "xingshuai"], ["zhu"]],
	re_caochong: ["male", "wei", 3, ["rechengxiang", "renxin"]],
	ol_zhangzhang: ["male", "wu", 3, ["olzhijian", "olguzheng"], ["name:张|昭-张|纮"]],
	re_jsp_huangyueying: ["female", "qun", 3, ["rejiqiao", "relinglong"]],
	re_zhangsong: ["male", "shu", 3, ["qiangzhi", "rexiantu"]],
	re_zhuzhi: ["male", "wu", 4, ["reanguo"]],
	dc_caozhi: ["male", "wei", 3, ["reluoying", "dcjiushi"]],
	ol_huangzhong: ["male", "shu", 4, ["xinliegong", "remoshi"]],
	re_wenpin: ["male", "wei", 5, ["rezhenwei"]],
	re_guanzhang: ["male", "shu", 4, ["fuhun", "retongxin"], ["name:关|兴-张|苞"]],
	re_mazhong: ["male", "shu", 4, ["refuman"]],
	dc_chenqun: ["male", "wei", 3, ["repindi", "dcfaen"]],
	re_sundeng: ["male", "wu", 4, ["rekuangbi"]],
	re_caiyong: ["male", "qun", 3, ["rebizhuan", "retongbo"]],
	re_chengong: ["male", "qun", 3, ["remingce", "zhichi"]],
	re_xunyou: ["male", "wei", 3, ["reqice", "rezhiyu"], ["clan:颍川荀氏"]],
	dc_liru: ["male", "qun", 3, ["xinjuece", "dcmieji", "dcfencheng"]],
	re_zhuhuan: ["male", "wu", 4, ["refenli", "repingkou"]],
	ol_dianwei: ["male", "wei", 4, ["olqiangxi", "olninge"]],
	re_sp_taishici: ["male", "qun", 4, ["rejixu"], ["name:太史|慈"]],
	re_liufeng: ["male", "shu", 4, ["rexiansi"]],
	ol_xunyu: ["male", "wei", 3, ["quhu", "oljieming"], ["clan:颍川荀氏"]],
	re_liuchen: ["male", "shu", 4, ["rezhanjue", "reqinwang"], ["zhu"]],
	dc_gongsunzan: ["male", "qun", 4, ["dcyicong", "dcqiaomeng"], ["name:公孙|瓒"]],
	re_duji: ["male", "wei", 3, ["reandong", "reyingshi"]],
	re_jushou: ["male", "qun", 3, ["dcjianying", "dcshibei"]],
	re_zhanghe: ["male", "wei", 4, ["reqiaobian"]],
	dc_xushu: ["male", "shu", 4, ["rezhuhai", "xsqianxin"]],
	xin_gaoshun: ["male", "qun", 4, ["decadexianzhen", "decadejinjiu"]],
	re_guohuanghou: ["female", "wei", 3, ["rejiaozhao", "redanxin"], ["name:郭|null"]],
	re_xiahoushi: ["female", "shu", 3, ["reqiaoshi", "reyanyu"], ["name:夏侯|null"]],
	ol_lusu: ["male", "wu", 3, ["olhaoshi", "oldimeng"]],
	re_jiaxu: ["male", "qun", 3, ["rewansha", "reluanwu", "reweimu"]],
	re_guyong: ["male", "wu", 3, ["reshenxing", "rebingyi"]],
	xin_zhonghui: ["male", "wei", 4, ["xinquanji", "xinzili"], ["clan:颍川钟氏"]],
	re_caifuren: ["female", "qun", 3, ["reqieting", "rexianzhou"], ["name:蔡|null"]],
	re_guanping: ["male", "shu", 4, ["relongyin", "jiezhong"]],
	re_guotufengji: ["male", "qun", 3, ["rejigong", "shifei"], ["name:郭|图-逢|记"]],
	re_zhoucang: ["male", "shu", 4, ["rezhongyong"]],
	ol_zhurong: ["female", "shu", 4, ["juxiang", "lieren", "changbiao"], ["doublegroup:shu:qun"]],
	re_zhangchunhua: ["female", "wei", 3, ["rejueqing", "shangshi"]],
	re_gongsunyuan: ["male", "qun", 4, ["rehuaiyi"], ["name:公孙|渊"]],
	re_caozhen: ["male", "wei", 4, ["residi"]],
	re_fuhuanghou: ["female", "qun", 3, ["rezhuikong", "reqiuyuan"]],
	re_fazheng: ["male", "shu", 3, ["reenyuan", "rexuanhuo"]],
	xin_lingtong: ["male", "wu", 4, ["decadexuanfeng", "yongjin"]],
	xin_liubiao: ["male", "qun", 3, ["decadezishou", "decadezongshi"]],
	re_caoxiu: ["male", "wei", 4, ["qianju", "reqingxi"]],
	re_sunxiu: ["male", "wu", 3, ["reyanzhu", "rexingxue", "zhaofu"], ["zhu"]],
	ol_dengai: ["male", "wei", 4, ["oltuntian", "olzaoxian"]],
	re_gongsunzan: ["male", "qun", 4, ["reqiaomeng", "reyicong"], ["name:公孙|瓒"]],
	re_manchong: ["male", "wei", 3, ["rejunxing", "yuce"]],
	xin_yufan: ["male", "wu", 3, ["xinzhiyan", "xinzongxuan"]],
	dc_bulianshi: ["female", "wu", 3, ["dcanxu", "dczhuiyi"]],
	re_hanhaoshihuan: ["male", "wei", 4, ["reshenduan", "reyonglve"], ["name:韩|浩-史|涣"]],
	re_panzhangmazhong: ["male", "wu", 4, ["reduodao", "reanjian"], ["name:潘|璋-马|忠"]],
	re_wangyi: ["female", "wei", 4, ["zhenlie", "miji"]],
	re_madai: ["male", "shu", 4, ["mashu", "reqianxi"]],
	xin_xusheng: ["male", "wu", 4, ["decadepojun"]],
	re_taishici: ["male", "wu", 4, ["tianyi", "hanzhan"], ["name:太史|慈"]],
	re_masu: ["male", "shu", 3, ["resanyao", "rezhiman"]],
	re_sunluban: ["female", "wu", 3, ["rechanhui", "rejiaojin"]],
	xin_handang: ["male", "wu", 4, ["xingongji", "xinjiefan"]],
	yujin_yujin: ["male", "wei", 4, ["decadezhenjun"], ["die:xin_yujin.mp3"]],
	re_caozhang: ["male", "wei", 4, ["xinjiangchi"]],
	re_chengpu: ["male", "wu", 4, ["ollihuo", "rechunlao"]],
	re_quancong: ["male", "wu", 4, ["xinyaoming"]],
	re_liaohua: ["male", "shu", 4, ["xindangxian", "xinfuli"]],
	re_guohuai: ["male", "wei", 4, ["decadejingce"]],
	re_wuyi: ["male", "shu", 4, ["xinbenxi"], ["clan:陈留吴氏"]],
	re_zhuran: ["male", "wu", 4, ["xindanshou"]],
	ol_pangtong: ["male", "shu", 3, ["ollianhuan", "olniepan"], []],
	re_zhangyi: ["male", "shu", 5, ["rewurong", "reshizhi"]],
	xin_wuguotai: ["female", "wu", 3, ["xinganlu", "xinbuyi"], ["name:丁|null"]],
	re_caocao: ["male", "wei", 4, ["new_rejianxiong", "rehujia"], ["zhu"]],
	re_simayi: ["male", "wei", 3, ["refankui", "reguicai"], ["name:司马|懿"]],
	re_guojia: ["male", "wei", 3, ["tiandu", "new_reyiji"]],
	re_zhangliao: ["male", "wei", 4, ["new_retuxi"]],
	re_xuzhu: ["male", "wei", 4, ["new_reluoyi"]],
	re_xiahoudun: ["male", "wei", 4, ["reganglie", "new_qingjian"], ["name:夏侯|惇"]],
	re_zhangfei: ["male", "shu", 4, ["olpaoxiao", "oltishen"]],
	re_zhaoyun: ["male", "shu", 4, ["ollongdan", "olyajiao"]],
	re_guanyu: ["male", "shu", 4, ["new_rewusheng", "new_yijue"]],
	re_machao: ["male", "shu", 4, ["mashu", "retieji"]],
	re_zhouyu: ["male", "wu", 3, ["reyingzi", "refanjian"]],
	re_lvmeng: ["male", "wu", 4, ["keji", "qinxue", "rebotu"]],
	re_ganning: ["male", "wu", 4, ["qixi", "fenwei"]],
	re_luxun: ["male", "wu", 3, ["reqianxun", "relianying"]],
	re_daqiao: ["female", "wu", 3, ["reguose", "liuli"], ["name:桥|null"]],
	re_huanggai: ["male", "wu", 4, ["rekurou", "zhaxiang"]],
	re_lvbu: ["male", "qun", 5, ["wushuang", "new_liyu"]],
	re_huatuo: ["male", "qun", 3, ["jijiu", "new_reqingnang"]],
	re_liubei: ["male", "shu", 4, ["rerende", "rejijiang"], ["zhu"]],
	re_diaochan: ["female", "qun", 3, ["lijian", "rebiyue"], ["name:null|null"]],
	re_huangyueying: ["female", "shu", 3, ["rejizhi", "reqicai"]],
	re_sunquan: ["male", "wu", 4, ["rezhiheng", "rejiuyuan"], ["zhu"]],
	re_sunshangxiang: ["female", "wu", 3, ["xiaoji", "rejieyin"]],
	re_zhenji: ["female", "wei", 3, ["reluoshen", "qingguo"]],
	re_zhugeliang: ["male", "shu", 3, ["reguanxing", "kongcheng"], ["name:诸葛|亮"]],
	re_huaxiong: ["male", "qun", 6, ["reyaowu", "shizhan"]],

	re_zhangjiao: ["male", "qun", 3, ["xinleiji", "xinguidao", "xinhuangtian"], ["zhu"]],
	xin_yuji: ["male", "qun", 3, ["reguhuo"]],
	re_zuoci: ["male", "qun", 3, ["rehuashen", "rexinsheng"]],

	ol_xiahouyuan: ["male", "wei", 4, ["xinshensu", "shebian"], ["name:夏侯|渊"]],
	caoren: ["male", "wei", 4, ["xinjushou", "xinjiewei"]],
	ol_weiyan: ["male", "shu", 4, ["xinkuanggu", "reqimou"]],
	ol_xiaoqiao: ["female", "wu", 3, ["oltianxiang", "olhongyan", "piaoling"], ["name:桥|null"]],
	zhoutai: ["male", "wu", 4, ["buqu", "fenji"]],
	ol_pangde: ["male", "qun", 4, ["mashu", "rejianchu"]],
	ol_xuhuang: ["male", "wei", 4, ["olduanliang", "oljiezi"]],
	ol_sp_zhugeliang: ["male", "shu", 3, ["bazhen", "olhuoji", "olkanpo", "cangzhuo"], ["name:诸葛|亮"]],
	ol_yanwen: ["male", "qun", 4, ["olshuangxiong"], ["name:颜|良-文|丑"]],
	ol_yuanshao: ["male", "qun", 4, ["olluanji", "olxueyi"], ["zhu"]],
	re_menghuo: ["male", "shu", 4, ["huoshou", "rezaiqi", "twqiushou"], ["zhu", "doublegroup:shu:qun"]],
	ol_dongzhuo: ["male", "qun", 8, ["oljiuchi", "roulin", "benghuai", "olbaonue"], ["zhu"]],
	ol_sunjian: ["male", "wu", "4/5", ["gzyinghun", "wulie", "twpolu"], ["zhu"]],
	re_caopi: ["male", "wei", 3, ["rexingshang", "refangzhu", "songwei"], ["zhu"]],
	ol_jiangwei: ["male", "shu", 4, ["oltiaoxin", "olzhiji"]],
	ol_caiwenji: ["female", "qun", 3, ["olbeige", "duanchang"]],
	ol_liushan: ["male", "shu", 3, ["xiangle", "olfangquan", "olruoyu"], ["zhu"]],

	re_sunce: ["male", "wu", 4, ["oljiang", "olhunzi", "olzhiba"], ["zhu"]],
	re_jianyong: ["male", "shu", 3, ["reqiaoshui", "jyzongshi"]],
};

export default characters;
