window.noname_package = {
	character: {
		//经典标包＋神话再临
		standard: "标准",
		shenhua: "神话再临",
		extra: "神将",
		//一将成名+界限突破
		yijiang: "一将成名",
		refresh: "界限突破",
		//新时代通用武将
		sp: "璀璨星河",
		sp2: "系列专属",
		newjiang: "新一将成名",
		//OL服
		onlyOL: "OL专属",
		yingbian: "文德武备",
		clan: "门阀士族",
		//十周年服
		huicui: "群英荟萃",
		xianding: "限定专属",
		//移动服+外服
		mobile: "移动版",
		shiji: "始计篇",
		sb: "谋攻篇",
		tw: "外服武将",
		//各服联动+怀旧
		collab: "联动卡",
		old: "怀旧",
		//线下系列
		offline: "线下武将",
		jsrg: "江山如故",
		sixiang: "四象封印",
		//DIY系列
		diy: "DIY",
		ddd: "3D精选",
		key: "Key",
		yxs: "英雄杀",
		hearth: "炉石传说",
		gwent: "昆特牌",
		mtg: "万智牌",
		ow: "守望先锋",
		swd: "轩辕剑",
		gujian: "古剑奇谭",
		xianjian: "仙剑奇侠传",
	},
	card: {
		standard: "标准",
		extra: "军争",
		guozhan: "国战",
		yingbian: "应变篇",
		yongjian: "用间篇",
		sp: "忠胆英杰",
		zhulu: "逐鹿天下",
		yunchou: "运筹帷幄",
		zhenfa: "阵法",
		swd: "轩辕剑",
		gujian: "古剑奇谭",
		hearth: "炉石传说",
		gwent: "昆特牌",
		mtg: "万智牌",
		xianxia: "线下卡牌",
		huanlekapai: "欢乐卡牌",
	},
	play: {
		boss: "诸神降临",
		cardpile: "牌堆补充",
		wuxing: "五行生克",
		coin: "富甲天下",
	},
	mode: {
		identity: "身份",
		guozhan: "国战",
		versus: "对决",
		connect: "联机",
		boss: "挑战",
		doudizhu: "斗地主",
		single: "单挑",
		chess: "战棋",
		tafang: "塔防",
		stone: "炉石",
		brawl: "乱斗",
	},
	submode: {
		identity: {
			normal: "身份模式",
			zhong: "忠胆英杰",
			purple: "3v3v2",
		},
		guozhan: {
			normal: "国战模式",
			mingjiang: "明将国战",
		},
		versus: {
			four: "四人对抗",
			three: "统率三军",
			two: "欢乐成双",
			jiange: "守卫剑阁",
			siguo: "四国争霸",
			standard: "自由对决",
		},
		chess: {
			combat: "战棋模式",
			three: "战棋统率",
			leader: "战棋君主",
		},
		single: {
			normal: "新1v1",
		},
	},
	background: {
		ol_bg: "龙纹",
		planetarian_bg: "星梦",
		heaven_bg: "红烧",
		kyoani_bg: "京都",
		key_bg: "键社",
		xiaowu_bg: "小无",
		noname_bg: "璀璨",
		wuming_bg: "无名",
		zhulin_bg: "竹林",
		shengshi_bg: "盛世",
		taoyuan_bg: "桃园",
		zhanhuo_bg: "战火",
		huangtian_bg: "黄天",
		september_bg: "九月",
		yinxiang_bg: "印象",
		zhanyun_bg: "战云",
		beipan_bg: "背叛",
		lanting_bg: "兰亭",
		lingju_bg: "灵雎",
		sanying_bg: "三英",
		wangshi_bg: "往事",
		xiongxin_bg: "雄心",
		xinsha_bg: "新杀",
	},
	music: {
		music_phliosophy: "Philosophy of ours",
		music_diaochan: "貂蝉",
		music_shezhan: "舌战群儒",
		music_danji: "千里走单骑",
		music_jifeng: "祭风",
		music_jilve: "极略",
	},
	font: {
		xiaozhuan: "方正小篆体",
		xinwei: "华文新魏_GBK",
		huangcao: "方正黄草_GBK",
		yuanli: "方正北魏楷书_GBK",
		xingkai: "方正行楷_GBK",
		shousha: "方正隶变_GBK",
	},
	theme: {
		woodden: "木纹",
		music: "音乐",
		simple: "简约",
	},
};
