window.noname_update={
	version:'1.9.53.1',
	update:'1.9.53',
	changeLog:[
		'bug修复'
	],
	players:[
		'sunshangxiang'
	],
	files:[
		'card/standard.js',
		'character/gwent.js',
		'character/rank.js',
		'character/standard.js',
		'character/yijiang.js',
		'layout/mobile/equip.css',
		'layout/newlayout/equip.css'
	]
};