window.noname_update={
    version:'1.9.0.1',
    changeLog:[
        'bug修复',
    ],
    files:{
        global:[
            'game/game.js',
            'game/config.js',
            'card/standard.js',
            'character/hearth.js',
            'character/ow.js',
            'character/yijiang.js',
            'mode/brawl.js',
            'layout/mode/chess.css',
            'layout/default/layout.css',
            'layout/mobile/layout.css',
        ],
        '1.9.0':[]
    }
}
