const characters = {
	ddd_handang: ["male", "wu", 4, ["dddxianxi"]],
	// ddd_wuzhi:["male","wei",3,["dddlingyong","dddxuxiao"]],
	ddd_xujing: ["male", "shu", 3, ["dddxuyu", "dddshijian"]],
	// ddd_caomao:["male","wei",3,["dddtaisi","dddquche","dddqianlong"],["zhu"]],
	// ddd_xinxianying:["female","wei",3,["ddddongcha","dddzhijie"]],
	ddd_xianglang: ["male", "shu", 3, ["dddqiahua", "dddfusi", "dddtuoji"]],
	ddd_yujin: ["male", "wei", 4, ["dddzhengjun"]],
	ddd_liuye: ["male", "wei", 3, ["dddchashi", "dddqice"]],
	ddd_baosanniang: ["female", "shu", 3, ["dddzhilian", "dddjijian"]],
	// ddd_zhenji:['female','wei',3,['dddmiaoxing','dddfushi']],
	ddd_zhaoang: ["male", "wei", 4, ["dddfenji"]],
	ddd_zhouchu: ["male", "wu", 5, ["dddxiaheng"]],
	ddd_liuba: ["male", "shu", 3, ["dddfengzheng", "dddyulv"]],
	ddd_jianshuo: ["male", "qun", 4, ["dddfenye", "dddshichao"]],
	ddd_guanning: ["male", "qun", 3, ["dddyouxue", "dddchengjing"]],
	ddd_dingfeng: ["male", "wu", 4, ["dddduanbing"]],
	ddd_caoshuang: ["male", "wei", 5, ["dddzhuanshe", "dddweiqiu"]],
	ddd_xuelingyun: ["female", "wei", 3, ["dddlianer", "dddanzhi"]],
	ddd_liuhong: ["male", "qun", 4, ["dddshixing", "ddddanggu", "dddfuzong"], ["zhu"]],
	ddd_xiahouxuan: ["male", "wei", 3, ["dddlanghuai", "dddxuanlun"], ["name:夏侯|玄"]],
	ddd_zhangkai: ["male", "qun", "3/4", ["dddjiexing", "dddbailei"]],
	ddd_liangxi: ["male", "wei", 4, ["dddtongyu"]],
	ddd_wangkanglvkai: ["male", "shu", 4, ["dddbingjian"], ["name:王|伉-吕|凯"]],
	// ddd_sunliang:['male','wu',3,['ddddiedang','dddanliu','dddguiying'],['zhu']],
	ddd_lie: ["female", "wu", 3, ["dddyeshen", "dddqiaoduan"]],
	ddd_kebineng: ["male", "qun", 4, ["dddxiaoxing", "dddlangzhi", "dddfuyi"], ["zhu"]],
	ddd_qianzhao: ["male", "wei", 4, ["dddyuanzhen", "dddzhishu"]],
	ddd_zhangmiao: ["male", "qun", 4, ["dddxiaxing"]],
	ddd_zhangcheng: ["male", "wu", 3, ["dddjuxian", "dddjungui"]],
	ddd_liuchong: ["male", "qun", 4, ["dddjinggou", "dddmoyan"]],
	ddd_luoxian: ["male", "shu", 4, ["dddshilie"]],
};

export default characters;
