const characters = {
	old_shixie: ["male", "qun", 3, ["biluan", "lixia"]],
	panfeng: ["male", "qun", 4, ["kuangfu"]],
	old_shen_zhaoyun: ["male", "shen", 2, ["oldjuejing", "oldlonghun"], ["shu"]],
	old_guanyinping: ["female", "shu", 3, ["xueji_old", "oldhuxiao", "oldwuji"]],
	old_caocao: ["male", "shen", 3, ["junkguixin", "feiying"], ["die_audio"]],
	old_chendao: ["male", "shu", 4, ["drlt_wanglie"]],
	old_liyan: ["male", "shu", 3, ["duliang", "fulin"]],
	old_guanzhang: ["male", "shu", 4, ["old_fuhun"]],
	new_caoren: ["male", "wei", 4, ["moon_jushou", "jiewei"]],
	huangzhong: ["male", "shu", 4, ["liegong"]],
	junk_sunquan: ["male", "shen", 4, ["dili", "yuheng"], ["wei"]],
	old_dingfeng: ["male", "wu", 4, ["fenxun", "duanbing"]],
	old_huanghao: ["male", "shu", 3, ["oldqinqing", "oldhuisheng"]],
	oldre_liubiao: ["male", "qun", 3, ["zishou", "zongshi"]],
	old_liubiao: ["male", "qun", 4, ["oldzishou", "zongshi"]],
	old_gaoshun: ["male", "qun", 4, ["xianzhen", "jinjiu"]],
	old_caorui: ["male", "wei", 3, ["huituo", "oldmingjian", "xingshuai"], ["zhu"]],
	old_handang: ["male", "wu", 4, ["oldgongji", "oldjiefan"]],
	old_yangzhi: ["female", "jin", 3, ["wanyi", "maihuo"]],
	old_yangyan: ["female", "jin", 3, ["xuanbei", "xianwan"]],
	madai: ["male", "shu", 4, ["mashu", "oldqianxi"]],
	xuhuang: ["male", "wei", 4, ["gzduanliang"]],
	junk_simayi: ["male", "jin", 3, ["buchen", "smyyingshi", "xiongzhi", "quanbian"], ["hiddenSkill"]],
	fazheng: ["male", "shu", 3, ["enyuan", "xuanhuo"]],
	ol_yuanshu: ["male", "qun", 4, ["wangzun", "tongji"]],
	pangde: ["male", "qun", 4, ["mashu", "mengjin"]],
	ol_huaxiong: ["male", "qun", 6, ["new_reyaowu"]],
	old_wangyun: ["male", "qun", 4, ["wylianji", "moucheng"], ["clan:太原王氏"]],
	old_xiaoqiao: ["female", "wu", 3, ["tianxiang", "hongyan"]],
	weiyan: ["male", "shu", 4, ["kuanggu"]],
	xiahouyuan: ["male", "wei", 4, ["shensu"]],
	old_zhangxingcai: ["female", "shu", 3, ["oldshenxian", "qiangwu"]],
	old_fuhuanghou: ["female", "qun", 3, ["oldzhuikong", "oldqiuyuan"]],
	old_caochong: ["male", "wei", 3, ["oldrenxin", "oldchengxiang"]],
	yuji: ["male", "qun", 3, ["old_guhuo"]],
	zhangjiao: ["male", "qun", 3, ["leiji", "guidao", "huangtian"], ["zhu"]],
	old_zhangfei: ["male", "shu", 4, ["new_repaoxiao", "new_tishen"]],
	old_zhaoyun: ["male", "shu", 4, ["longdan", "new_yajiao"]],
	old_huatuo: ["male", "qun", 3, ["jijiu", "chulao"]],
	old_guanyu: ["male", "shu", 4, ["wusheng", "yijue"]],
	old_caochun: ["male", "wei", 4, ["shanjia"]],
	masu: ["male", "shu", 3, ["xinzhan", "huilei"]],
	xushu: ["male", "shu", 3, ["xswuyan", "jujian"], ["border:wei"]],
	liru: ["male", "qun", 3, ["juece", "mieji", "fencheng"]],
	xin_yujin: ["male", "wei", 4, ["jieyue"]],
	//lusu:['male','wu',3,['haoshi','dimeng']],
	//yuanshao:['male','qun',4,['luanji','xueyi'],['zhu']],
	old_zhonghui: ["male", "wei", 3, ["zzhenggong", "zquanji", "zbaijiang"], ["clan:颍川钟氏"]],
	old_xusheng: ["male", "wu", 4, ["pojun"]],
	old_zhuran: ["male", "wu", 4, ["olddanshou"]],
	old_lingtong: ["male", "wu", 4, ["oldxuanfeng"]],
	old_caoxiu: ["male", "wei", 4, ["taoxi"]],
	old_caozhen: ["male", "wei", 4, ["sidi"]],
	old_maliang: ["male", "shu", 3, ["xiemu", "naman"]],
	old_chenqun: ["male", "wei", 3, ["dingpin", "oldfaen"]],
	old_zhuhuan: ["male", "wu", 4, ["youdi"]],
	old_zhuzhi: ["male", "wu", 4, ["anguo"]],

	old_zhugezhan: ["male", "shu", 3, ["old_zuilun", "old_fuyin"]],
	ol_zhangrang: ["male", "qun", 3, ["xintaoluan"], ["sex:male_castrated"]],
	//ol_manchong:['male','wei',3,['yuce','junxing']],
	old_guanqiujian: ["male", "wei", 4, ["drlt_zhenrong", "drlt_hongju"], []],
	old_wanglang: ["male", "wei", 3, ["gushe", "jici"]],
	old_wangyi: ["female", "wei", 3, ["oldzhenlie", "oldmiji"]],
	re_yujin: ["male", "wei", 4, ["yizhong"]],
};

export default characters;
