export default {
	"#yizhong1": "不先为备，何以待敌？",
	"#yizhong2": "稳重行军，百战不殆！",
	"#xin_yujin:die": "呃，晚节不保……",
	"#xiahouyuan:die": "竟然……比我还……快……",
	"#weiyan:die": "谁敢杀我？！呃啊……",
	"#xuhuang:die": "一顿不吃，饿得慌……",
	"#huangtian2_zhangjiao1": "岁在甲子，天下大吉！",
	"#huangtian2_zhangjiao2": "苍天已死，黄天当立！",
	"#zhangjiao:die": "黄天，也死了……",
	"#wuyan1": "唉，一切尽在不言中。",
	"#wuyan2": "嘘，言多必失啊。",
	"#jujian1": "将军岂愿抓牌乎？",
	"#jujian2": "我看好你！",
	"#xushu:die": "娘……孩儿不孝……向您……请罪……",
	"#old_guhuo1": "你信吗？",
	"#old_guhuo2": "猜猜看哪~",
	"#yuji:die": "竟然……被猜到了……",
	"#old_fuhun1": "呐喊破敌，锐不可挡！",
	"#old_fuhun2": "匹夫之勇，插标卖首！",
	"#old_guanzhang:die": "父亲，我来了……",
	"#huangzhong:die": "不得不服老啦~",
};
