const characters = {
	chengjichengcui: ["male", "wei", 6, ["oltousui", "olchuming"], ["name:成|济-成|倅", "border:jin"]],
	wangxiang: ["male", "jin", 3, ["bingxin"]],
	jin_jiachong: ["male", "jin", 3, ["xiongshu", "jianhui"]],
	xuangongzhu: ["female", "jin", 3, ["gaoling", "qimei", "ybzhuiji"], ["hiddenSkill", "name:司马|null"]],
	xinchang: ["male", "jin", 3, ["canmou", "congjian"]],
	yangzhi: ["female", "jin", 3, ["xinwanyi", "maihuo"]],
	yangyan: ["female", "jin", 3, ["xinxuanbei", "xianwan"]],
	ol_huaxin: ["male", "wei", 3, ["caozhao", "olxibing"]],
	zhongyan: ["female", "jin", 3, ["bolan", "yifa"], ["clan:颍川钟氏"]],
	weiguan: ["male", "jin", 3, ["zhongyun", "shenpin"]],
	cheliji: ["male", "qun", 4, ["chexuan", "qiangshou"], ["name:彻里|吉"]],
	simazhou: ["male", "jin", 4, ["recaiwang", "naxiang"], ["name:司马|伷"]],
	ol_lisu: ["male", "qun", 3, ["qiaoyan", "xianzhu"]],
	jin_yanghuiyu: ["female", "jin", 3, ["huirong", "ciwei", "caiyuan"], ["hiddenSkill"]],
	shibao: ["male", "jin", 4, ["zhuosheng"]],
	jin_zhangchunhua: ["female", "jin", 3, ["huishi", "qingleng", "xuanmu"], ["hiddenSkill"]],
	jin_simayi: ["male", "jin", 3, ["buchen", "smyyingshi", "xiongzhi", "xinquanbian"], ["hiddenSkill", "name:司马|懿"]],
	jin_wangyuanji: ["female", "jin", 3, ["shiren", "yanxi"], ["hiddenSkill"]],
	jin_simazhao: ["male", "jin", 3, ["tuishi", "xinchoufa", "zhaoran", "chengwu"], ["zhu", "hiddenSkill", "name:司马|昭"]],
	jin_xiahouhui: ["female", "jin", 3, ["baoqie", "jyishi", "shiduo"], ["hiddenSkill", "name:夏侯|徽"]],
	jin_simashi: ["male", "jin", "3/4", ["taoyin", "yimie", "ruilve", "tairan"], ["hiddenSkill", "zhu", "name:司马|师"]],
	zhanghuyuechen: ["male", "jin", 4, ["xijue"], ["name:张|虎-乐|綝"]],
	duyu: ["male", "jin", 4, ["sanchen", "zhaotao"]],
};

export default characters;
