const characters = {
	star_sunjian: ["male", "qun", "4/5", ["starruijun", "stargangyi"]],
	liqueguosi: ["male", "qun", 4, ["xiongsuan"]],
	star_zhangchunhua: ["female", "wei", 3, ["starliangyan", "starminghui"]],
	star_yuanshao: ["male", "qun", 4, ["starxiaoyan", "starzongshi", "starjiaowang", "staraoshi"], ["zhu"]],
	star_dongzhuo: ["male", "qun", 5, ["starweilin", "starzhangrong", "starhaoshou"], ["zhu"]],
	star_yuanshu: ["male", "qun", 4, ["starcanxi", "starpizhi", "starzhonggu"], ["zhu"]],
	star_caoren: ["male", "wei", 4, ["starsujun", "starlifeng"]],
	mp_liuling: ["male", "jin", 3, ["mpjiusong", "mpmaotao", "mpbishi"], ["doublegroup:wei:qun:jin"]],
	dc_jikang: ["male", "wei", 3, ["new_qingxian", "dcjuexiang"]],
	dc_jsp_guanyu: ["male", "wei", 4, ["new_rewusheng", "dcdanji"]],
	dc_mengda: ["male", "wei", 4, ["dclibang", "dcwujie"]],
	//dc_fuwan:['male','qun',4,['dcmoukui']],
	guānning: ["male", "shu", 3, ["dcxiuwen", "longsong"]],
	sunhuan: ["male", "wu", 4, ["dcniji"]],
	sunlang: ["male", "shu", 4, ["dctingxian", "dcbenshi"]],
	shiyi: ["male", "wu", 3, ["dccuichuan", "dczhengxu"]],
	dc_hujinding: ["female", "shu", "3/6", ["dcdeshi", "dcwuyuan", "huaizi"]],
	liyixiejing: ["male", "wu", 4, ["dcdouzhen"]],
	mushun: ["male", "qun", 4, ["dcjinjian", "dcshizhao"]],
	dc_zhaoyǎn: ["male", "wei", 3, ["dcfuning", "dcbingji"]],
	wangwei: ["male", "qun", 4, ["dcruizhan", "dcshilie"]],
	dc_huban: ["male", "wei", 4, ["dcchongyi"]],
	niufu: ["male", "qun", "4/7", ["dcxiaoxi", "xiongrao"]],
	bianxi: ["male", "wei", 4, ["dunxi"]],
	fengfang: ["male", "qun", 3, ["dcditing", "dcbihuo"]],
	qinyilu: ["male", "qun", 3, ["piaoping", "tuoxian", "chuaili"]],
	yanrou: ["male", "wei", 4, ["choutao", "xiangshu"]],
	dc_zhuling: ["male", "wei", 4, ["dczhanyi"]],
	licaiwei: ["female", "wei", 3, ["yijiao", "qibie"]],
	yanfuren: ["female", "qun", 3, ["channi", "nifu"]],
	haomeng: ["male", "qun", 7, ["xiongmang"]],
	re_pangdegong: ["male", "qun", 3, ["heqia", "yinyi"]],
	hanmeng: ["male", "qun", 4, ["jieliang", "quanjiu"]],
	xinping: ["male", "qun", 3, ["fuyuan", "zhongjie", "yongdi"]],
	zhangning: ["female", "qun", 3, ["tianze", "difa"]],
	tongyuan: ["male", "qun", 4, ["chaofeng", "chuanshu"]],
	sp_mifangfushiren: ["male", "shu", 4, ["fengshi"]],
	re_nanhualaoxian: ["male", "qun", 4, ["gongxiu", "jinghe"]],
	dufuren: ["female", "wei", 3, ["yise", "shunshi"]],
	caoanmin: ["male", "wei", 4, ["xianwei"]],
	re_zoushi: ["female", "qun", 3, ["rehuoshui", "reqingcheng"]],
	qiuliju: ["male", "qun", "4/6", ["koulve", "qljsuiren"]],
	re_hucheer: ["male", "qun", 4, ["redaoji", "fuzhong"]],
	re_dongcheng: ["male", "qun", 4, ["xuezhao"]],
	tangji: ["female", "qun", 3, ["kangge", "jielie"]],
	zhangheng: ["male", "qun", 8, ["dangzai", "liangjue"]],
	duanwei: ["male", "qun", 4, ["langmie"]],
	re_niujin: ["male", "wei", 4, ["recuorui", "reliewei"]],
	zhangmiao: ["male", "qun", 4, ["mouni", "zongfan"]],
	liangxing: ["male", "qun", 4, ["lulve", "lxzhuixi"]],
	caosong: ["male", "wei", 4, ["cslilu", "csyizheng"]],
	re_taoqian: ["male", "qun", 3, ["zhaohuo", "reyixiang", "reyirang"]],
	zhaozhong: ["male", "qun", 6, ["yangzhong", "huangkong"]],
	hanfu: ["male", "qun", 4, ["hfjieying", "weipo"]],
	re_quyi: ["male", "qun", 4, ["refuqi", "jiaozi"]],
	dongxie: ["female", "qun", 4, ["dcjiaoxia", "dchumei"]],
	wangrong: ["female", "qun", 3, ["minsi", "jijing", "zhuide"]],
	ol_dingyuan: ["male", "qun", 4, ["cixiao", "xianshuai"]],
	re_hejin: ["male", "qun", 4, ["spmouzhu", "spyanhuo"]],
	re_hansui: ["male", "qun", 4, ["spniluan", "spweiwu"]],
	liuhong: ["male", "qun", 4, ["yujue", "tuxing"]],
	zhujun: ["male", "qun", 4, ["gongjian", "kuimang"]],
	re_maliang: ["male", "shu", 3, ["rexiemu", "heli"], []],
	caobuxing: ["male", "wu", 3, ["moying", "juanhui"], []],
	lijue: ["male", "qun", "4/6", ["xinfu_langxi", "xinfu_yisuan"], []],
	zhangji: ["male", "qun", 4, ["xinfu_lveming", "xinfu_tunjun"], []],
	fanchou: ["male", "qun", 4, ["xinxingluan"], []],
	guosi: ["male", "qun", 4, ["xinfu_tanbei", "xinfu_sidao"], []],
	lvkai: ["male", "shu", 3, ["xinfu_tunan", "xinfu_bijing"], []],
	zhanggong: ["male", "wei", 3, ["xinfu_zhenxing", "xinfu_qianxin"], []],
	weiwenzhugezhi: ["male", "wu", 4, ["xinfu_fuhai"], []],
	beimihu: ["female", "qun", 3, ["zongkui", "guju", "baijia"]],
	xurong: ["male", "qun", 4, ["xinfu_xionghuo", "xinfu_shajue"], []],
	zhangqiying: ["female", "qun", 3, ["xinfu_falu", "xinfu_dianhua", "xinfu_zhenyi"], []],
	sp_liuqi: ["male", "qun", 3, ["rewenji", "sptunjiang"]],
	xf_tangzi: ["male", "wei", 4, ["xinfu_xingzhao"], []],
	xf_huangquan: ["male", "shu", 3, ["xinfu_dianhu", "xinfu_jianji"], []],
	xf_sufei: ["male", "wu", 4, ["xinfu_lianpian"], []],
	xushao: ["male", "qun", 4, ["pingjian"]],
	xinpi: ["male", "wei", 3, ["xpchijie", "yinju"]],
	lisu: ["male", "qun", 2, ["lslixun", "lskuizhu"]],
	zhangwen: ["male", "wu", 3, ["songshu", "sibian"]],
	mangyachang: ["male", "qun", 4, ["spjiedao"], []],
	xugong: ["male", "wu", 3, ["biaozhao", "yechou"], []],
	zhangchangpu: ["female", "wei", 3, ["yanjiao", "xingshen"], []],
	gaolan: ["male", "qun", 4, ["xiying"]],
	sp_shenpei: ["male", "qun", 3, ["gangzhi", "beizhan"]],
	xunchen: ["male", "qun", 3, ["fenglve", "mouzhi"], ["clan:颍川荀氏"]],
	sp_zhanghe: ["male", "qun", 4, ["yuanlve"]],
	sp_xuyou: ["male", "qun", 3, ["spshicai", "spfushi"]],
	chunyuqiong: ["male", "qun", 5, ["cangchu", "sushou", "liangying"]],
	lvkuanglvxiang: ["male", "qun", 4, ["liehou", "qigong"]],
};

export default characters;
