const characterReplaces = {
	lijue: ["lijue", "ns_lijue"],
	fanchou: ["fanchou", "tw_fanchou", "ns_fanchou"],
	zhangji: ["zhangji", "ns_zhangji"],
	zhangchangpu: ["ol_zhangchangpu", "zhangchangpu", "sp_zhangchangpu"],
	huangfusong: ["huangfusong", "sp_huangfusong", "jsrg_huangfusong", "old_huangfusong"],
	dingyuan: ["ol_dingyuan", "dingyuan"],
	quyi: ["quyi", "re_quyi"],
	hansui: ["hansui", "re_hansui", "xin_hansui", "jsrg_hansui"],
	jin_simashi: ["dc_simashi", "jin_simashi", "simashi"],
	jin_yanghuiyu: ["jin_yanghuiyu", "yanghuiyu"],
	taoqian: ["re_taoqian", "taoqian"],
	jsp_liubei: ["jsrg_liubei", "jsp_liubei"],
	dongcheng: ["re_dongcheng", "dongcheng"],
	hucheer: ["re_hucheer", "hucheer", "tw_hucheer"],
	nanhualaoxian: ["re_nanhualaoxian", "nanhualaoxian", "jsrg_nanhualaoxian"],
	pangdegong: ["re_pangdegong", "pangdegong"],
	zhujun: ["ol_zhujun", "zhujun", "sp_zhujun", "jsrg_zhujun"],
	tw_liuhong: ["liuhong", "tw_liuhong", "jsrg_liuhong"],
	re_hejin: ["hejin", "re_hejin", "tw_hejin", "jsrg_hejin"],
	hujinding: ["dc_hujinding", "ol_hujinding", "hujinding"],
	caosong: ["caosong", "sp_caosong"],
	re_niujin: ["niujin", "re_niujin", "tw_niujin"],
	haomeng: ["haomeng", "tw_haomeng"],
	zhangning: ["zhangning", "tw_zhangning"],
	caoanmin: ["caoanmin", "ns_caoanmin"],
	duanwei: ["duanwei", "junk_duanwei"],
	xushao: ["xushao", "jsrg_xushao"],
	huban: ["ol_huban", "dc_huban", "mb_huban"],
	mengda: ["ol_mengda", "dc_mengda", "pe_mengda"],
	jsp_guanyu: ["jsp_guanyu", "dc_jsp_guanyu", "jsrg_guanyu"],
	mushun: ["mushun", "sp_mushun"],
	wangjun: ["dc_wangjun", "wangjun"],
	zoushi: ["re_zoushi", "jsrg_zoushi"],
	zhangmancheng: ["dc_zhangmancheng", "tw_zhangmancheng"],
};

export default characterReplaces;
