const characterSort = {
	sp_whlw: ["xurong", "lijue", "zhangji", "fanchou", "guosi", "duanwei", "liangxing", "zhangheng", "tangji", "niufu", "dongxie", "liqueguosi"],
	sp_zlzy: ["zhangqiying", "lvkai", "zhanggong", "weiwenzhugezhi", "beimihu"],
	sp_longzhou: ["xf_tangzi", "xf_huangquan", "xf_sufei", "sp_liuqi"],
	sp_zizouqi: ["mangyachang", "xugong", "zhangchangpu"],
	sp_sbfm: ["lisu", "xinpi", "zhangwen"],
	sp_guandu: ["sp_zhanghe", "xunchen", "sp_shenpei", "gaolan", "lvkuanglvxiang", "chunyuqiong", "sp_xuyou", "xinping", "hanmeng"],
	sp_qihuan: ["zhaozhong", "re_hejin", "fengfang", "mushun"],
	sp_binglin: ["re_niujin", "sp_mifangfushiren", "licaiwei", "dc_zhaoyan", "shiyi", "sunlang", "sunhuan", "dc_mengda"],
	sp_danqi: ["dufuren", "qinyilu", "bianxi", "dc_huban", "dc_hujinding", "dc_zhaoyǎn", "wangwei", "liyixiejing", "guānning", "dc_jsp_guanyu"],
	sp_fenghuo: ["re_nanhualaoxian", "tongyuan", "zhangning", "re_pangdegong"],
	sp_huangjin: ["liuhong", "zhujun", "re_hansui", "xushao"],
	sp_fadong: ["ol_dingyuan", "wangrong", "re_quyi", "hanfu"],
	sp_xuzhou: ["re_taoqian", "caosong", "zhangmiao", "qiuliju"],
	sp_zhongyuan: ["re_hucheer", "re_zoushi", "caoanmin", "re_dongcheng"],
	sp_xiaohu: ["haomeng", "yanfuren", "yanrou", "dc_zhuling"],
	sp_star: ["star_caoren", "star_yuanshu", "star_dongzhuo", "star_yuanshao", "star_zhangchunhua", "star_sunjian"],
	mini_qixian: ["mp_liuling"],
	sp2_waitforsort: ["caobuxing", "re_maliang", "dc_jikang"],
};

const characterSortTranslate = {
	sp_whlw: "文和乱武",
	sp_zlzy: "逐鹿中原",
	sp_longzhou: "同舟共济",
	sp_zizouqi: "自走棋",
	sp_sbfm: "上兵伐谋",
	sp_shengun: "三国奇人传",
	sp_guandu: "官渡之战",
	sp_huangjin: "列传·黄巾之乱",
	sp_fadong: "列传·诸侯伐董",
	sp_xuzhou: "列传·徐州风云",
	sp_qihuan: "戚宦之争",
	sp_zhongyuan: "列传·中原狼烟",
	sp_binglin: "兵临城下",
	sp_xiaohu: "列传·虓虎悲歌",
	sp_fenghuo: "烽火连天",
	sp_danqi: "千里单骑",
	sp_star: "将星系列",
	mini_qixian: "小程序·竹林七贤",
	sp2_waitforsort: "等待分包",
};

export { characterSort, characterSortTranslate };
