const characterSort = {
	sp2_tianliang: ["duji"],
	sp2_tiantong: ["sp_taishici"],
	sp2_tianxiang: ["lvdai", "liuyao"],
	sp2_qisha: ["re_zhangliang"],
	sp2_whlw: ["lijue", "zhangji", "fanchou", "guosi", "duanwei", "liangxing", "zhangheng", "tangji", "niufu", "dongxie", "liqueguosi"],
	sp2_zltx: ["lvkai", "zhanggong", "weiwenzhugezhi", "beimihu"],
	sp2_longzhou: ["xf_tangzi", "xf_huangquan", "xf_sufei", "sp_liuqi"],
	sp2_zizouqi: ["mangyachang", "xugong", "zhangchangpu"],
	sp2_sbfm: ["lisu", "xinpi", "zhangwen"],
	sp2_guandu: ["sp_zhanghe", "xunchen", "sp_shenpei", "gaolan", "lvkuanglvxiang", "chunyuqiong", "sp_xuyou", "xinping", "hanmeng"],
	sp2_qihuan: ["zhaozhong", "re_hejin", "fengfang", "mushun"],
	sp2_binglin: ["re_niujin", "sp_mifangfushiren", "licaiwei", "dc_zhaoyan", "shiyi", "sunlang", "sunhuan", "dc_mengda", "dc_zhaoyǎn", "wangwei", "liyixiejing"],
	sp2_danqi: ["dufuren", "qinyilu", "bianxi", "dc_huban", "dc_hujinding", "guānning", "dc_jsp_guanyu"],
	sp2_fenghuo: ["re_nanhualaoxian", "tongyuan", "zhangning", "re_pangdegong"],
	sp2_huangjin: ["liuhong", "zhujun", "re_hansui", "xushao"],
	sp2_fadong: ["ol_dingyuan", "wangrong", "re_quyi", "hanfu"],
	sp2_xuzhou: ["re_taoqian", "caosong", "zhangmiao", "qiuliju"],
	sp2_zhongyuan: ["re_hucheer", "re_zoushi", "caoanmin", "re_dongcheng"],
	sp2_xiaohu: ["haomeng", "yanfuren", "yanrou", "dc_zhuling"],
	sp2_qunxiong: ["chezhou", "hansong", "matie"],
	sp2_tianshu: ["star_yuanshu", "star_dongzhuo", "star_yuanshao"],
	sp2_yuheng: ["star_caoren", "star_zhangchunhua"],
	sp2_kaiyang: ["star_sunjian"],
	sp2_yaoguang: ["star_sunshangxiang"],
	sp2_tianxuan: ["star_xunyu"],
	sp2_waitforsort: ["caobuxing", "re_maliang", "dc_jikang", "star_zhangzhao"],
};

const characterSortTranslate = {
	sp2_tianliang: "星火燎原·天梁",
	sp2_tiantong: "星火燎原·天同",
	sp2_tianxiang: "星火燎原·天相",
	sp2_qisha: "星火燎原·七杀",
	sp2_longzhou: "活动场·同舟共济",
	sp2_guandu: "活动场·官渡之战",
	sp2_whlw: "南征北战·文和乱武",
	sp2_zltx: "南征北战·逐鹿天下",
	sp2_zizouqi: "南征北战·自走棋",
	sp2_sbfm: "南征北战·上兵伐谋",
	sp2_qihuan: "南征北战·戚宦之争",
	sp2_binglin: "南征北战·兵临城下",
	sp2_fenghuo: "南征北战·烽火连天",
	sp2_danqi: "南征北战·千里单骑",
	sp2_xiaohu: "武将列传·虓虎悲歌",
	sp2_qunxiong: "武将列传·群雄伺动",
	sp2_zhongyuan: "武将列传·中原狼烟",
	sp2_huangjin: "武将列传·黄巾之乱",
	sp2_fadong: "武将列传·诸侯伐董",
	sp2_xuzhou: "武将列传·徐州风云",
	sp2_tianshu: "星河璀璨·天枢",
	sp2_yuheng: "星河璀璨·玉衡",
	sp2_kaiyang: "星河璀璨·开阳",
	sp2_yaoguang: "星河璀璨·瑶光",
	sp2_tianxuan: "星河璀璨·天璇",
	sp2_waitforsort: "等待分包",
};

export { characterSort, characterSortTranslate };
