const characters = {
	liuba: ["male", "shu", 3, ["duanbi", "tongduo"]],
	sp_zhujun: ["male", "qun", 4, ["xinyangjie", "xinjuxiang", "houfeng"]],
	sp_huangfusong: ["male", "qun", 4, ["spzhengjun", "spshiji", "sptaoluan"]],
	sp_lvfan: ["male", "wu", 3, ["mbdiaodu", "mbdiancai", "spyanji"]],
	sp_jiangqing: ["male", "wu", 4, ["spjianyi", "spshangyi"]],
	sp_jiangwan: ["male", "shu", 3, ["spzhenting", "spjincui"]],
	sp_zhangchangpu: ["female", "wei", 3, ["spdifei", "spyanjiao"]],
	sp_cuiyan: ["male", "wei", 3, ["spyajun", "spzundi"]],
	sp_huaman: ["female", "shu", 4, ["spxiangzhen", "spfangzong", "spxizhan"]],
	sp_gaolan: ["male", "qun", 4, ["spjungong", "spdengli"]],
	sunyi: ["male", "wu", 4, ["zaoli"]],
	sp_wangshuang: ["male", "wei", 4, ["yiyong", "shanxie"]],
	sp_zongyu: ["male", "shu", 3, ["zhibian", "yuyan"]],
	yuanhuan: ["male", "wei", 3, ["qingjue", "fengjie"]],
	sp_chendong: ["male", "wu", 4, ["spyilie", "spfenming"]],
	db_wenyang: ["male", "wei", 4, ["dbquedi", "dbzhuifeng", "dbchongjian", "dbchoujue"], ["doublegroup:wei:wu"]],
	sp_yanghu: ["male", "qun", 3, ["mingfa", "rongbei"]],
	qiaogong: ["male", "wu", 3, ["yizhu", "luanchou"]],
	liuzhang: ["male", "qun", 3, ["jutu", "yaohu", "rehuaibi"], ["zhu"]],
	sp_zhangwen: ["male", "wu", 3, ["gebo", "spsongshu"]],
	zhangzhongjing: ["male", "qun", 3, ["jishi", "xinliaoyi", "binglun"]],
	sp_xujing: ["male", "shu", 3, ["boming", "ejian"]],
	sp_huaxin: ["male", "wei", 3, ["yuanqing", "shuchen"]],
	xiangchong: ["male", "shu", 4, ["guying", "muzhen"]],
	caizhenji: ["female", "wei", 3, ["sheyi", "tianyin"]],
	sp_kongrong: ["male", "qun", 3, ["xinlirang", "xinmingshi"]],
	zhouchu: ["male", "wu", 4, ["xianghai", "rechuhai"]],
	wangfuzhaolei: ["male", "shu", 4, ["xunyi"]],
	wangling: ["male", "wei", 4, ["xingqi", "xinzifu", "mibei"], ["clan:太原王氏"]],
	wujing: ["male", "wu", 4, ["heji", "liubing"]],
	sp_mifuren: ["female", "shu", 3, ["xinguixiu", "qingyu"]],
	sp_xinpi: ["male", "wei", 3, ["spyinju", "spchijie"]],
	feiyi: ["male", "shu", 3, ["mjshengxi", "fyjianyu"]],
	sp_bianfuren: ["female", "wei", 3, ["spwanwei", "spyuejian"]],
	sp_duyu: ["male", "qun", 4, ["spwuku", "spsanchen"]],
	luotong: ["male", "wu", 4, ["qinzheng"]],
	sp_wangcan: ["male", "wei", 3, ["spqiai", "spshanxi"]],
	sp_chenzhen: ["male", "shu", 3, ["shameng"]],
	sp_sunshao: ["male", "wu", 3, ["mjdingyi", "mjzuici", "mjfubi"]],
	sp_xunchen: ["male", "qun", 3, ["mjweipo", "mjchenshi", "mjmouzhi"], ["clan:颍川荀氏"]],
};

export default characters;
