const characterReplaces = {
	wangcan: ["wangcan", "sp_wangcan", "tw_wangcan"],
	sunshao: ["sunshao", "sp_sunshao"],
	xunchen: ["xunchen", "re_xunchen", "sp_xunchen", "tw_xunchen", "clan_xunchen"],
	xinpi: ["xinpi", "sp_xinpi"],
	duyu: ["duyu", "dc_duyu", "sp_duyu", "pk_sp_duyu"],
	zhangwen: ["zhangwen", "sp_zhangwen"],
	ol_bianfuren: ["ol_bianfuren", "sp_bianfuren", "tw_bianfuren"],
	wangshuang: ["wangshuang", "sp_wangshuang"],
	huaman: ["huaman", "sp_huaman"],
	gaolan: ["gaolan", "dc_gaolan", "sp_gaolan"],
	cuiyan: ["cuiyan", "sp_cuiyan"],
	wujing: ["wujing", "tw_wujing"],
	zhouchu: ["jin_zhouchu", "zhouchu", "tw_zhouchu"],
	liuzhang: ["liuzhang", "tw_liuzhang"],
	chenzhen: ["sp_chenzhen", "tw_chenzhen"],
	feiyi: ["ol_feiyi", "feiyi", "tw_feiyi"],
	wangling: ["dc_wangling", "wangling", "tw_wangling", "clan_wangling"],
	qiaogong: ["qiaogong", "tw_qiaogong"],
	sp_chendong: ["sp_chendong", "tw_chendong", "chendong"],
	sp_jiangqing: ["sp_jiangqing", "tw_jiangqing", "jiangqing"],
	kongrong: ["dc_kongrong", "sp_kongrong", "jsrg_kongrong", "kongrong"],
	dc_mifuren: ["dc_mifuren", "sp_mifuren"],
};

export default characterReplaces;
