export default {
	"#jsrgzhenglve1": "臣奉陛下之命，以伐乱臣。",
	"#jsrgzhenglve2": "陛下且安坐宫中，待臣之捷报。",
	"#jsrgzhenglve3": "齐桓之功，唯霸可彰王道。",
	"#jsrgzhenglve4": "晋公亦霸，然亦躬奉周王。",
	"#jsrghuilie1": "奉辞伐罪，旌麾南指，欲请将军会猎于吴。",
	"#jsrghuilie2": "宝雕弓，金鈚箭，臣乞为陛下猎天下之不臣。",
	"#jsrgpingrong1": "兵贵神速，勿失此讨贼良机。",
	"#jsrgpingrong2": "以战平戎，以武止戈。",
	"#jsrgpingrong3": "治世匡以仁德，乱世当用重典。",
	"#jsrg_caocao:die": "本欲征西讨贼，为国效命，奈何天命……唉……",
	"#jsrgjishan1": "刀兵在我，而百姓何辜耶？",
	"#jsrgjishan2": "备宁愿一死，只求百姓得安。",
	"#jsrgjishan3": "民若得安，则天下安矣！",
	"#jsrgjishan4": "勿以恶小而为之，勿以善小而不为。",
	"#jsrgzhenqiao1": "剑出鞘命，引得龙吟海内！",
	"#jsrgzhenqiao2": "鲲鹏之志，志在天下苍生！",
	"#jsrg_liubei:die": "楼桑羽葆，黄粱一梦……",
	"#jsrgpingtao1": "今当夷汝三族，县示四海。",
	"#jsrgpingtao2": "歃血为盟，誓诛此国贼。",
	"#jsrgjuelie1": "传令所部兵马，定绝董贼后路。",
	"#jsrgjuelie2": "董贼势败在即，诸公何故不前。",
	"#jsrgjuelie3": "火势刻不容缓，全军速速进发。",
	"#jsrgjuelie4": "洛阳已在眼下，莫让董贼轻逃。",
	"#jsrg_sunjian:die": "若违此誓，某必为万箭穿心！",
};
