export default {
	wuguotai: ["sunjian", "sunshangxiang"],
	zhangchunhua: ["simayi"],
	caozhi: ["zhenji"],
	xunyou: ["xunyu"],
	xushu: ["liubei"],
	lingtong: ["ganning"],
	chengong: ["lvbu"],
	bulianshi: ["sunquan"],
	fuhuanghou: ["liuxie"],
	sunluban: ["quancong"],
	caifuren: ["liubiao"],
	xiahoushi: ["zhangfei"],
	zhoucang: ["guanyu"],
	guanping: ["guanyu"],
	sundeng: ["sunquan", "zhoufei"],
	liuchen: ["liushan"],
	yujin: ["xiahoudun"],
	fazheng: ["liubei"],
	zhonghui: ["jiangwei"],
};
