'use strict';
card.basic={
	connect:true,
	card:{
		yexingchengzhang:{
			cost:2,
			class:'druid',
		},
		ailongbakebaohuzhe:{
			cost:8,
			class:'druid',
			attack:8,
			health:8,
			skill:{
				taunt:true
			},
		},
		dongwuhuoban:{
			cost:3,
			class:'hunter'
		},
		xunshoushi:{
			cost:4,
			class:'hunter',
			attack:4,
			health:3,
			skill:{
				battlecry:{}
			},
		},
		hanbingjian:{
			cost:2,
			class:'mage',
		},
		shuiyuansu:{
			cost:4,
			class:'mage',
			attack:3,
			health:6,
			skill:{
				freeze:{}
			},
		},
		fengxian:{
			cost:4,
			class:'paladin'
		},
		liewangshouwei:{
			cost:7,
			class:'paladin',
			attack:5,
			health:6,
			skill:{
				battlecry:{}
			}
		},
		zhenyanshudun:{
			cost:1,
			class:'priest'
		},
		beijunmushi:{
			cost:1,
			class:'priest',
			attack:1,
			health:3,
			skill:{
				heal:{}
			}
		},
		beici:{
			cost:0,
			class:'rogue'
		},
		cikezhiren:{
			cost:5,
			class:'rogue',
			attack:3,
			duration:4,
		},
		yaoshu:{
			cost:3,
			class:'shaman'
		},
		huoyuansu:{
			cost:6,
			class:'shaman',
			attack:6,
			health:5,
			skill:{
				battlecry:{}
			}
		},
		diyulieyan:{
			cost:4,
			class:'warlock'
		},
		xukongxingzhe:{
			cost:1,
			class:'warlock',
			attack:1,
			health:3,
			race:'deamon',
			skill:{
				taunt:true
			}
		},
		chiyanzhanfu:{
			cost:2,
			class:'warrior',
			attack:3,
			duration:2,
		},
		zhangezhihuiguan:{
			cost:3,
			class:'warrior',
			attack:2,
			health:3,
			skill:{
				zhihui:{}
			}
		},
		lansaizhanshi:{
			cost:2,
			class:'neutral',
			attack:2,
			health:1,
			race:'murlock',
			skill:{
				charge:true
			}
		},
		zhurufamingjia:{
			cost:4,
			class:'neutral',
			attack:2,
			health:4,
			skill:{
				battlecry:{}
			}
		}
	},
	translate:{
		yexingchengzhang:'野性成长',
		yexingchengzhang_info:'获得一个空的法力水晶',
		ailongbakebaohuzhe:'埃隆巴克保护者',
		ailongbakebaohuzhe_info:'嘲讽',
		dongwuhuoban:'动物伙伴',
		dongwuhuoban_info:'随机召唤一个野兽伙伴',
		xunshoushi:'驯兽师',
		xunshoushi_info:'<b>战吼</b>：使一个友方野兽获得+2/+2并获得<b>嘲讽</b>',
		hanbingjian:'寒冰箭',
		hanbingjian_info:'对一个角色造成3点伤害，并使其<b>冻结</b>',
		shuiyuansu:'水元素',
		shuiyuansu_info:'<b>冻结</b>任何受到该随从伤害的角色',
		fengxian:'奉献',
		fengxian_info:'对所有敌人造成2点伤害',
		liewangshouwei:'列王守卫',
		liewangshouwei_info:'<b>战吼</b>：为你的英雄恢复6点生命值',
		zhenyanshudun:'真言术·盾',
		zhenyanshudun_info:'使一个随从获得+2生命值。抽一张牌',
		beijunmushi:'北郡牧师',
		beijunmushi_info:'每当一个随从获得治疗时，抽一张牌',
		beici:'背刺',
		beici_info:'对一个未受伤的随从造成2点伤害',
		cikezhiren:'刺客之刃',
		cikezhiren_info:' ',
		yaoshu:'妖术',
		yaoshu_info:'使一个随从变形成为一个0/1并具有<b>嘲讽</b>的青蛙',
		huoyuansu:'火元素',
		huoyuansu_info:'<b>战吼</b>：造成3点伤害',
		diyulieyan:'地狱烈焰',
		diyulieyan_info:'对所有角色造成3点伤害',
		xukongxingzhe:'虚空行者',
		xukongxingzhe_info:'<b>嘲讽</b>',
		chiyanzhanfu:'炽炎战斧',
		chiyanzhanfu_info:' ',
		zhangezhihuiguan:'战歌指挥官',
		zhangezhihuiguan_info:'你的具有<b>冲锋</b>的随从获得+1攻击力',
		lansaizhanshi:'蓝鳃战士',
		lansaizhanshi_info:'<b>冲锋</b>',
		zhurufamingjia:'侏儒发明家',
		zhurufamingjia_info:'<b>战吼</b>：抽一张牌',
	},
}
