card.compensate={
	list:[
		["diamond",3,'guohe'],
		['club',8,'guohe'],
		['spade',13,'guohe'],

		['diamond',8,'shunshou'],
		['heart',5,'shunshou'],

		["club",10,"wuxie"],
		["spade",10,"wuxie"],
		["spade",11,"wuxie"],

		['heart',8,'tao'],
		['heart',10,'tao'],

		["heart",10,"sha","fire"],
		["diamond",4,"sha","fire"],
		["heart",5,"sha","fire"],
		["spade",4,"sha","thunder"],
		["spade",5,"sha","thunder"],
		["club",5,"sha","thunder"],
		["spade",9,"sha","thunder"],
		["club",8,"sha"],
		["club",10,"sha"],
		["club",2,"sha"],
		["club",10,"sha"],
		["spade",10,"sha"],
		["spade",10,"sha"],
		["spade",11,"sha"],
		["spade",6,"sha"],
		["club",2,"sha"],
		["club",8,"sha"],
		["spade",9,"sha"],

		["spade",4,"sha"],
		["spade",7,"sha"],
		["spade",1,"sha"],
		["club",4,"sha"],
		["club",7,"sha"],
		["club",2,"sha"],

		["heart",10,"sha","fire"],
		["diamond",4,"sha","fire"],
		["heart",5,"sha","fire"],
		["spade",4,"sha","thunder"],
		["spade",5,"sha","thunder"],
		["club",5,"sha","thunder"],
		["spade",9,"sha","thunder"],
		["club",8,"sha"],
		["club",10,"sha"],
		["club",2,"sha"],
		["club",10,"sha"],
		["spade",10,"sha"],
		["spade",10,"sha"],
		["spade",11,"sha"],
		["spade",6,"sha"],
		["club",2,"sha"],
		["club",8,"sha"],
		["spade",9,"sha"],

		["spade",4,"sha"],
		["spade",7,"sha"],
		["spade",1,"sha"],
		["club",4,"sha"],
		["club",7,"sha"],
		["club",2,"sha"],

		["spade",4,"sha"],
		["spade",7,"sha"],
		["spade",1,"sha"],
		["club",4,"sha"],
		["club",7,"sha"],
		["club",2,"sha"],

		["heart",11,"shan"],
		["heart",12,"shan"],
		["diamond",6,"shan"],
		["heart",11,"shan"],
		["heart",8,"shan"],
		["diamond",5,"shan"],
		["diamond",2,"shan"],
		["heart",11,"shan"],
		["heart",12,"shan"],
		["heart",12,"shan"],
		["heart",4,"shan"],
		["heart",4,"shan"],
		["diamond",6,"shan"],
		["diamond",7,"shan"],
		["heart",11,"shan"],
		["heart",12,"shan"],
		["diamond",6,"shan"],
		["diamond",7,"shan"],

		["diamond",6,"shan"],
		["diamond",7,"shan"],
		["heart",11,"shan"],
		["heart",12,"shan"],
		["diamond",6,"shan"],
		["diamond",7,"shan"],

		["club",5,"tiesuo"],
		["spade",8,"tiesuo"],
	],
}
