'use strict';
card.mingzhong={
	card:{
		shengdong:{
            fullskin:true,
            enable:'phaseUse',
            type:'trick',
        },
        zengbin:{
            fullskin:true,
            enable:'phaseUse',
            type:'trick',
        },
        caomu:{
            fullskin:true,
            enable:'phaseUse',
            type:'delay',
        }
	},
	translate:{
        shengdong:'声东击西',
		shengdong_info:'出牌阶段，对距离为1的一名角色使用。你交给目标角色一张手牌，若如此做，其将两张牌交给另一名由你选择的其他角色',
        zengbin:'增兵减灶',
        zengbin_info:'出牌阶段，对一名角色使用。目标角色摸三张牌，然后选择一项：1.弃置一张非基本牌；2.弃置两张牌',
        caomu:'草木皆兵',
        caomu_info:'出牌阶段，对一名其他角色使用。将【草木皆兵】放置于该角色的判定区里，若判定结果不为梅花：摸牌阶段，目标角色少摸一张牌；摸牌阶段结束时，与其距离为1的角色各摸一张牌',
	},
	list:[
		["spade",1,'caomu'],
		["club",3,'caomu'],
		["heart",12,'shengdong',],
        ["club",9,'shengdong'],
		["spade",9,'shengdong'],
        ["diamond",4,'zengbin'],
        ["heart",6,'zengbin'],
        ["spade",7,'zengbin'],
	],
}
