const characters = {
	liuxiecaojie: ["male", "qun", 2, ["dcjuanlv", "dcqixin"]],
	dc_zhaoyun: ["male", "shen", 1, ["boss_juejing", "dclonghun", "dczhanjiang"], ["shu", "InitFilter:noZhuHp:noZhuSkill"]],
	dc_sunce: ["male", "wu", 4, ["dcshuangbi"]],
	nezha: ["male", "qun", 3, ["dcsantou", "dcfaqi"], ["InitFilter:noZhuHp", "name:李|哪吒"]],
	dc_caocao: ["male", "wei", 4, ["dcjianxiong"]],
	dc_liubei: ["male", "shu", 4, ["dcrende"]],
	dc_sunquan: ["male", "wu", 4, ["dczhiheng"]],
	zhutiexiong: ["male", "qun", 3, ["dcbianzhuang"], ["die:true", "die:2"]],
	xiaoyuehankehan: ["male", "qun", 3, ["dctongliao", "dcwudao"], ["die:true", "die:3", "name:null|null"]],
	libai: ["male", "qun", 3, ["dclbjiuxian", "dcshixian"], ["die:true", "die:2"]],
	sunwukong: ["male", "qun", 3, ["dcjinjing", "dccibei", "dcruyi"]],
	longwang: ["male", "qun", 3, ["dclonggong", "dcsitian"], ["name:敖|广"]],
	taoshen: ["male", "qun", 3, ["dcnutao"], ["name:伍|子胥"]],
	sunyang: ["male", "wu", 4, ["clbshuijian"]],
	yeshiwen: ["female", "wu", 3, ["clbjisu", "clbshuiyong"]],
	sp_jiben: ["male", "qun", 3, ["spduanzhi", "spduyi"]],
	sp_fuhuanghou: ["female", "qun", 3, ["spcangni", "spmixin"]],
	sp_fuwan: ["male", "qun", 3, ["spfengyin", "spchizhong"]],
	old_lingju: ["female", "qun", 3, ["jieyuan", "fenxin_old"], ["name:吕|null"]],
	sp_mushun: ["male", "qun", 4, ["moukui"]],
	dc_wuyi: ["male", "shu", 4, ["dcbenxi"]],
	quyuan: ["male", "qun", 3, ["dcqiusuo", "dclisao"], ["name:芈|原"]],
	xin_sunquan: ["male", "wu", 3, ["dchuiwan", "dchuanli"]],
	wuhujiang: ["male", "shu", 4, ["olhuyi"], ["name:关|羽-张|飞-赵|云-马|超-黄|忠", "die:true", "die:5"]],
	dc_noname: ["male", "qun", 3, ["dcchushan"], ["name:null|null"]],
	ol_jsrg_caocao: ["male", "qun", 4, ["oldingxi", "olnengchen", "olhuojie"], ["character:jsrg_caocao"]],
	jiangziya: ["male", "qun", 3, ["xingzhou", "lieshen"], ["name:姜|尚"]],
	shengongbao: ["male", "qun", 3, ["zhuzhou", "yaoxian"]],
	nanjixianweng: ["male", "qun", 3, ["xwshoufa", "fuzhao"], ["name:null|null"]],
};

export default characters;
