const characters = {
	dc_zhaoyun: ["male", "shen", 1, ["boss_juejing", "dclonghun", "dczhanjiang"], ["shu", "InitFilter:noZhuHp:noZhuSkill"]],
	dc_sunce: ["male", "wu", 4, ["dcshuangbi"]],
	nezha: ["male", "qun", 3, ["dcsantou", "dcfaqi"], ["InitFilter:noZhuHp"]],
	dc_caocao: ["male", "wei", 4, ["dcjianxiong"]],
	dc_liubei: ["male", "shu", 4, ["dcrende"]],
	dc_sunquan: ["male", "wu", 4, ["dczhiheng"]],
	zhutiexiong: ["male", "qun", 3, ["dcbianzhuang"]],
	wu_zhutiexiong: ["male", "qun", 3, ["dcbianzhuang"], ["unseen"]],
	xiaoyuehankehan: ["male", "qun", 3, ["dctongliao", "dcwudao"], ["die_audio:xiaoyuehankehan:xiaoyuehankehan2:xiaoyuehankehan3"]],
	libai: ["male", "qun", 3, ["dclbjiuxian", "dcshixian"], ["die_audio:libai:libai2"]],
	sunwukong: ["male", "qun", 3, ["dcjinjing", "dccibei", "dcruyi"]],
	longwang: ["male", "qun", 3, ["dclonggong", "dcsitian"]],
	taoshen: ["male", "qun", 3, ["dcnutao"]],
	sunyang: ["male", "wu", 4, ["clbshuijian"]],
	yeshiwen: ["female", "wu", 3, ["clbjisu", "clbshuiyong"]],
	sp_jiben: ["male", "qun", 3, ["spduanzhi", "spduyi"]],
	sp_fuhuanghou: ["female", "qun", 3, ["spcangni", "spmixin"]],
	sp_fuwan: ["male", "qun", 3, ["spfengyin", "spchizhong"]],
	old_lingju: ["female", "qun", 3, ["jieyuan", "fenxin_old"]],
	sp_mushun: ["male", "qun", 4, ["moukui"]],
	dc_wuyi: ["male", "shu", 4, ["dcbenxi"]],
};

export default characters;
