const characters = {
	sb_zhugejin: ["male", "wu", 3, ["sbhuanshi", "sbhongyuan", "sbmingzhe"], ["name:诸葛|瑾"]],
	sb_jiaxu: ["male", "qun", 3, ["sbwansha", "sbluanwu", "sbweimu"]],
	sb_handang: ["male", "wu", 4, ["sbgongqi", "sbjiefan"]],
	sb_gongsunzan: ["male", "qun", 4, ["sbyicong", "sbqiaomeng"], ["name:公孙|瓒"]],
	sb_gaoshun: ["male", "qun", 4, ["sbxianzhen", "sbjinjiu"]],
	sb_xiahoudun: ["male", "wei", 4, ["sbganglie", "sbqingjian"], ["name:夏侯|惇"]],
	sb_xunyu: ["male", "wei", 3, ["sbquhu", "sbjieming"]],
	sb_caopi: ["male", "wei", 3, ["sbxingshang", "sbfangzhu", "sbsongwei"], ["zhu"]],
	sb_guanyu: ["male", "shu", 4, ["sbwusheng", "sbyijue"]],
	sb_huangyueying: ["female", "shu", 3, ["sbjizhi", "sbqicai"]],
	sb_sp_zhugeliang: ["male", "shu", 3, ["sbhuoji", "sbkanpo"], ["name:诸葛|亮"]],
	sb_zhanghe: ["male", "wei", 4, ["sbqiaobian"]],
	sb_yujin: ["male", "wei", 4, ["sbxiayuan", "sbjieyue"]],
	sb_huaxiong: ["male", "qun", "3/4/1", ["new_reyaowu", "sbyangwei"]],
	liucheng: ["female", "qun", 3, ["splveying", "spyingwu"]],
	sp_yangwan: ["female", "qun", 3, ["spmingxuan", "spxianchou"]],
	sb_huangzhong: ["male", "shu", 4, ["sbliegong"]],
	sb_lvmeng: ["male", "wu", 4, ["sbkeji", "sbdujiang"]],
	sb_sunshangxiang: ["female", "shu", 4, ["sbjieyin", "sbliangzhu", "sbxiaoji"], ["border:wu"]],
	sb_sunquan: ["male", "wu", 4, ["sbzhiheng", "sbtongye", "sbjiuyuan"], ["zhu"]],
	sb_huanggai: ["male", "wu", 4, ["sbkurou", "sbzhaxiang"]],
	sb_zhouyu: ["male", "wu", 3, ["sbyingzi", "sbfanjian"]],
	sb_caoren: ["male", "wei", "4/4/1", ["sbjushou", "sbjiewei"]],
	sb_xiahoushi: ["female", "shu", 3, ["sbqiaoshi", "sbyanyu"], ["name:夏侯|null"]],
	sb_zhangjiao: ["male", "qun", 3, ["sbleiji", "sbguidao", "sbhuangtian"], ["zhu"]],
	sb_caocao: ["male", "wei", 4, ["sbjianxiong", "sbqingzheng", "sbhujia"], ["zhu"]],
	sb_zhenji: ["female", "wei", 3, ["sbluoshen", "qingguo"]],
	sb_ganning: ["male", "wu", 4, ["sbqixi", "sbfenwei"]],
	sb_machao: ["male", "shu", 4, ["mashu", "sbtieji"]],
	sb_xuhuang: ["male", "wei", 4, ["sbduanliang", "sbshipo"]],
	sb_zhangfei: ["male", "shu", 4, ["sbpaoxiao", "sbxieji"]],
	sb_zhaoyun: ["male", "shu", 4, ["sblongdan", "sbjizhu"]],
	sb_liubei: ["male", "shu", 4, ["sbrende", "sbzhangwu", "sbjijiang"], ["zhu"]],
	sb_jiangwei: ["male", "shu", "4/4/1", ["sbtiaoxin", "sbzhiji"]],
	sb_fazheng: ["male", "shu", 3, ["sbxuanhuo", "sbenyuan"]],
	sb_chengong: ["male", "qun", 3, ["sbmingce", "sbzhichi"]],
	sb_diaochan: ["female", "qun", 3, ["sblijian", "sbbiyue"], ["name:null|null"]],
	sb_yuanshao: ["male", "qun", 4, ["sbluanji", "sbxueyi"], ["zhu"]],
	sb_pangtong: ["male", "shu", 3, ["sblianhuan", "sbniepan"]],
	sb_sunce: ["male", "wu", 4, ["sbjiang", "sbhunzi", "sbzhiba"], ["zhu"]],
	sb_daqiao: ["female", "wu", 3, ["sbguose", "sbliuli"], ["name:桥|null"]],
	sb_liubiao: ["male", "qun", 3, ["sbzishou", "sbzongshi"]],
	sb_zhurong: ["female", "shu", 4, ["sblieren", "sbjuxiang"], ["doublegroup:shu:qun"]],
	sb_menghuo: ["male", "shu", 4, ["sbhuoshou", "sbzaiqi"], ["doublegroup:shu:qun"]],
	sb_yl_luzhi: ["male", "qun", 3, ["nzry_mingren", "sbzhenliang"]],
	sb_xiaoqiao: ["female", "wu", 3, ["sbtianxiang", "xinhongyan"], ["name:桥|null"]],
	sb_luxun: ["male", "wu", 3, ["sbqianxun", "sblianying"]],
};

export default characters;
