export default {
	ns_huangchengyan: "#g竹邀月",
	ns_sunchensunjun: "#gVenusjeu",
	ns_yuanxi: "#g食茸二十四",
	ns_caoshuang: "#g荬庀芬兰",
	ns_chentai: "#g荀彧III荀文若",
	ns_huangwudie: "#g你爸爸来了164",
	ns_sunyi: "#g无民氏4251",
	ns_zhangning: "#g如颍隋行1314",
	ns_yanghu: "#ginCenv",
	ns_ruanji: "#g伯约的崛起",
	ns_zanghong: "#g阿七",
	ns_limi: "#g-心若困兽-",
	ns_zhonglimu: "#gJG赛文♠7",
	prp_zhugeliang: "#g阿开木木W🍀",

	ns_luyusheng: "#g猫咪大院 - 魚と水",
	ns_caimao: "#gP尔号玩家◆",
	diy_wenyang: "#g最粗的梦想XD",
	ns_zuoci: "#bskystarwuwei",
	ns_lvzhi: "#bskystarwuwei",
	ns_wangyun: "#rSukincen",
	ns_guanlu: "#rSukincen",
	ns_xinnanhua: "#rSukincen",
	ns_nanhua: "#g戒除联盟",
	ns_shenpei: "#g戒除联盟",
	ns_huamulan: "#p哎别管我是谁",
	ns_jinke: "#p哎别管我是谁",
	ns_huangzu: "#r小芯儿童鞋",
	ns_lisu: "#r小芯儿童鞋",
	ns_yanliang: "#r丶橙续缘",
	ns_wenchou: "#r丶橙续缘",
	ns_caocao: "#r一瞬间丶遗忘",
	ns_caocaosp: "#g希望教主",
	ns_zhugeliang: "#p死不死什么的",
	ns_xinxianying: "#b扶苏公子",
	ns_zhangbao: "#b扶苏公子",
	ns_wangyue: "#p废城君",
	ns_sunjian: "#b兔子两只2",
	ns_lvmeng: "#b兔子两只2",
	ns_yujisp: "#b兔子两只2",
	ns_yuji: "#g蔚屿凉音",
	ns_simazhao: "#r一纸载春秋",
	ns_duangui: "#b宝宝酱紫萌萌哒",
	ns_masu: "#g修女",
	ns_zhangxiu: "#p本因坊神策",
	ns_yangyi: "#p本因坊神策",
	ns_liuzhang: "#r矮子剑薄荷糖",
	ns_mengyou: "#g残昼厄夜",
};
