export default {
	yuji: ["zuoci"],
	key_riki: ["key_rin", "key_saya", "key_kyousuke", "key_kud"],
	key_kud: ["key_harukakanata"],
	key_komari: ["key_rin", "key_sasami"],
	key_masato: ["key_kengo"],
	key_yuiko: ["key_harukakanata"],
	key_doruji: ["key_rin"],
	key_tomoya: ["key_nagisa", "key_sunohara", "key_kotomi"],
	key_ao: ["key_inari"],
	key_shiroha: ["key_umi"],
	key_shizuku: ["key_tsumugi"],
	key_yuzuru: ["key_hinata", "key_kanade", "key_ayato"],
	key_yuri: ["key_kanade", "key_abyusa"],
	key_hinata: ["key_yui"],
	key_iwasawa: ["key_hisako"],
	key_yuu: ["key_nao"],
	key_jojiro: ["key_yusa"],
	key_kaori: ["key_shiori"],
	key_chihaya: ["key_sakuya"],
	key_lucia: ["key_shizuru"],
};
