const characters = {
	sp_key_yuri: {
		sex: "female",
		group: "qun",
		hp: 4,
		skills: ["mubing", "ziqu", "diaoling"],
		groupBorder: "key",
		names: "仲村|由理",
	},
	key_lucia: {
		sex: "female",
		group: "key",
		hp: 2,
		maxHp: 3,
		skills: ["lucia_duqu", "lucia_zhenren"],
		names: "此花|露西娅",
	},
	key_kyousuke: {
		sex: "male",
		group: "key",
		hp: 4,
		skills: ["nk_shekong", "key_huanjie"],
		names: "枣|恭介",
	},
	key_yuri: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["yuri_xingdong", "key_huanjie", "yuri_wangxi"],
		isZhugong: true,
		names: "仲村|由理",
	},
	key_haruko: {
		sex: "female",
		group: "key",
		hp: 4,
		skills: ["haruko_haofang", "haruko_zhuishi"],
		names: "神尾|晴子",
	},
	key_umi: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["umi_chaofan", "umi_lunhui", "umi_qihuan"],
		names: "鹰原|羽未",
	},
	key_umi2: {
		sex: "female",
		group: "key",
		hp: 3,
		isUnseen: true,
		names: "鹰原|羽未",
	},
	key_rei: {
		sex: "male",
		group: "key",
		hp: 4,
		skills: ["xiandeng", "shulv", "xisheng"],
		names: "null|零",
	},
	key_komari: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["komari_tiankou", "komari_xueshang"],
		names: "神北|小毬",
	},
	key_yukine: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["yukine_wenzhou"],
		names: "宫泽|有纪宁",
	},
	key_yusa: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["yusa_yanyi", "yusa_misa", "dualside"],
		dualSideCharacter: "key_misa",
		names: "黑羽|柚咲",
	},
	key_misa: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["misa_yehuo", "misa_yusa", "dualside"],
		isUnseen: true,
		names: "黑羽|美砂",
	},
	key_masato: {
		sex: "male",
		group: "key",
		hp: 4,
		maxHp: 8,
		skills: ["masato_baoquan"],
		names: "井之原|真人",
	},
	key_iwasawa: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["iwasawa_yinhang", "iwasawa_mysong"],
		names: "岩泽|雅美",
	},
	key_kengo: {
		sex: "male",
		group: "key",
		hp: 4,
		skills: ["kengo_weishang", "kengo_guidui"],
		names: "宫泽|谦吾",
	},
	key_yoshino: {
		sex: "male",
		group: "key",
		hp: 4,
		skills: ["yoshino_jueyi"],
		names: "吉野|晴彦",
	},
	key_yui: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["yui_jiang", "yui_lieyin", "yui_takaramono"],
		names: "日向|由依",
	},
	key_tsumugi: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["tsumugi_mugyu", "tsumugi_huilang"],
		names: "文德斯|紬",
	},
	key_saya: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["saya_shouji", "saya_powei"],
		names: "朱鹭户|彩",
	},
	key_harukakanata: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["haruka_shuangche"],
		names: "三枝|叶留佳-二木|佳奈多",
	},
	key_inari: {
		sex: "female",
		group: "key",
		hp: 2,
		skills: ["inari_baiwei", "inari_huhun"],
		names: "空门|稻荷",
	},
	key_shiina: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["shiina_qingshen", "shiina_feiyan"],
		names: "null|椎名",
	},
	key_sunohara: {
		sex: "double",
		group: "key",
		hp: 3,
		hujia: 2,
		skills: ["sunohara_chengshuang", "sunohara_tiaoyin", "sunohara_jianren"],
		names: "春原|阳平-春原|芽衣",
	},
	key_rin: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["rin_baoqiu"],
		names: "枣|铃",
	},
	key_sasami: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["sasami_miaobian"],
		names: "笹濑川|佐佐美",
	},
	key_akane: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["akane_jugu", "akane_quanqing", "akane_yifu"],
		isZhugong: true,
		names: "千里|朱音",
	},
	key_doruji: {
		sex: "female",
		group: "key",
		hp: 16,
		skills: ["doruji_feiqu"],
		names: "null|多鲁基",
	},
	key_yuiko: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["yuiko_fenglun", "yuiko_dilve"],
		names: "来谷|唯湖",
	},
	key_riki: {
		sex: "double",
		group: "key",
		hp: 3,
		skills: ["riki_spwenji", "riki_nvzhuang", "riki_mengzhong"],
		names: "直枝|理树",
	},
	key_hisako: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["hisako_yinbao", "hisako_zhuanyun"],
		names: "渕田|久子",
	},
	key_hinata: {
		sex: "male",
		group: "key",
		hp: 4,
		skills: ["hinata_qiulve", "hinata_ehou"],
		names: "日向|秀树",
	},
	key_noda: {
		sex: "male",
		group: "key",
		hp: 4,
		skills: ["noda_fengcheng", "noda_xunxin"],
		names: "野田|null",
	},
	key_tomoya: {
		sex: "male",
		group: "key",
		hp: 4,
		skills: ["tomoya_shangxian", "tomoya_wangjin"],
		names: "冈崎|朋也",
	},
	key_nagisa: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["nagisa_tiandu", "nagisa_fuxin"],
		names: "古河|渚",
	},
	key_ayato: {
		sex: "male",
		group: "key",
		hp: 3,
		skills: ["ayato_jianshen", "ayato_zonghuan"],
		names: "直井|文人",
	},
	key_ao: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["ao_xishi", "ao_kuihun", "ao_shixin"],
		names: "空门|苍",
	},
	key_yuzuru: {
		sex: "male",
		group: "key",
		hp: 5,
		skills: ["yuzuru_wuxin", "yuzuru_deyi"],
		names: "音无|结弦",
	},
	sp_key_kanade: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["kanade_mapo", "kanade_benzhan"],
		names: "立华|奏",
	},
	key_mio: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["mio_tuifu", "mio_tishen"],
		names: "西园|美鱼",
	},
	key_midori: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["midori_nonghuan", "midori_tishen"],
		names: "西园|美鸟",
	},
	key_kyoko: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["kyoko_juwu", "kyoko_zhengyi"],
		names: "岬|镜子",
	},
	key_shizuru: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["shizuru_nianli", "shizuru_benzhan"],
		names: "中津|静流",
	},
	key_shiorimiyuki: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["shiorimiyuki_banyin", "shiorimiyuki_tingxian"],
		names: "关根|诗织-入江|美雪",
	},
	key_miki: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["miki_shenqiang", "miki_huanmeng", "miki_zhiluo"],
		names: "野村|美希",
	},
	key_shiori: {
		sex: "female",
		group: "key",
		hp: 2,
		maxHp: 3,
		skills: ["shiori_huijuan"],
		names: "美坂|栞",
	},
	key_kaori: {
		sex: "female",
		group: "key",
		hp: 3,
		maxHp: 4,
		skills: ["kaori_siyuan"],
		names: "美坂|香里",
	},
	key_akiko: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["akiko_dongcha"],
		names: "水濑|秋子",
	},
	key_abyusa: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["abyusa_jueqing", "abyusa_dunying"],
		names: "null|游佐",
	},
	key_godan: {
		sex: "male",
		group: "key",
		hp: 6,
		skills: ["godan_yuanyi", "godan_feiqu", "godan_xiaoyuan"],
		names: "松下|护驒",
	},
	key_yuu: {
		sex: "male",
		group: "key",
		hp: 3,
		skills: ["yuu_lveduo"],
		names: "乙坂|有宇",
	},
	key_ryoichi: {
		sex: "male",
		group: "key",
		hp: 4,
		skills: ["ryoichi_baoyi", "ryoichi_tuipi"],
		names: "三谷|良一",
	},
	key_kotori: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["kotori_yumo", "kotori_huazhan"],
		names: "神户|小鸟",
	},
	key_jojiro: {
		sex: "male",
		group: "key",
		hp: 4,
		skills: ["jojiro_shensu", "jojiro_shunying"],
		names: "高城|丈士朗",
	},
	key_shiroha: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["shiroha_yuzhao", "shiroha_guying", "shiroha_jiezhao"],
		names: "鸣濑|白羽",
	},
	key_shizuku: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["shizuku_sizhi", "shizuku_biyi", "shizuku_sanhua"],
		names: "水织|静久",
	},
	key_hiroto: {
		sex: "male",
		group: "key",
		hp: 3,
		skills: ["hiroto_huyu", "hiroto_tuolao"],
		names: "铃木|央人",
	},
	key_sakuya: {
		sex: "male",
		group: "key",
		hp: 3,
		skills: ["youlong", "luanfeng", "sakuya_junbu"],
		names: "凤|咲夜",
	},
	key_youta: {
		sex: "male",
		group: "key",
		hp: 4,
		skills: [],
		names: "成神|阳太",
	},
	key_rumi: {
		sex: "female",
		group: "key",
		hp: 3,
		maxHp: 4,
		skills: ["rumi_shuwu"],
		names: "七濑|留美",
	},
	key_chihaya: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["chihaya_liewu", "chihaya_youfeng"],
		names: "凤|千早",
	},
	key_yukito: {
		sex: "male",
		group: "key",
		hp: 4,
		skills: ["yukito_kongwu", "yukito_yaxiang"],
		names: "国崎|往人",
	},
	key_crow: {
		sex: "male",
		group: "key",
		hp: 4,
		skills: [],
		isUnseen: true,
		names: "null|空",
	},
	key_asara: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["asara_shelu", "asara_yingwei"],
		names: "井上|晶",
	},
	key_kotomi: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["kotomi_qinji", "kotomi_chuanxiang"],
		names: "一之濑|琴美",
	},
	key_mia: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["mia_shihui", "mia_qianmeng"],
		names: "藤川|米娅",
	},
	key_kano: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["kano_liezhen", "kano_poyu"],
		names: "雾岛|佳乃",
	},
	db_key_liyingxia: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["liyingxia_sanli", "liyingxia_zhenjun", "liyingxia_wumai"],
		doubleGroup: ["shu", "key"],
		names: "李|映夏",
	},
	key_erika: {
		sex: "female",
		group: "key",
		hp: 3,
		hujia: 2,
		skills: ["erika_shisong", "erika_yousheng"],
		names: "苍井|绘里香",
	},
	key_satomi: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["satomi_luodao", "satomi_daohai"],
		names: "藏|里见",
	},
	key_iriya: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["iriya_yinji", "iriya_haozhi"],
		names: "罗杰斯特·文斯卡娅|伊莉雅",
	},
	key_fuuko: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["fuuko_xingdiao", "fuuko_chuanyuan"],
		names: "伊吹|风子",
	},
	key_kagari: {
		sex: "female",
		group: "shen",
		groupInGuozhan: "key",
		hp: 3,
		skills: ["kagari_zongsi"],
		names: "未来来|篝",
	},
	key_shiki: {
		sex: "female",
		group: "shen",
		groupInGuozhan: "key",
		hp: 3,
		maxHp: 5,
		skills: ["shiki_omusubi"],
		names: "神山|识",
	},
	db_key_hina: {
		sex: "female",
		group: "shen",
		groupInGuozhan: "key",
		hp: 3,
		skills: ["hina_shenshi", "hina_xingzhi"],
		doubleGroup: ["key", "shen"],
		names: "佐藤|雏",
	},
	key_kud: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["kud_qiaoshou", "kud_buhui"],
		names: "能美|库特莉亚芙卡",
	},
	key_misuzu: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["misuzu_hengzhou", "misuzu_nongyin", "misuzu_zhongxing"],
		names: "神尾|观铃",
	},
	key_kamome: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["kamome_yangfan", "kamome_huanmeng", "kamome_jieban"],
		names: "久岛|鸥",
	},
	key_nao: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["nao_duyin", "nao_wanxin", "nao_shouqing"],
		names: "友利|奈绪",
	},
	key_yuuki: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["yuuki_yicha"],
		names: "冰室|忧希",
	},
	key_kotarou: {
		sex: "male",
		group: "key",
		hp: 3,
		skills: ["kotarou_rewrite", "kotarou_aurora"],
		names: "天王寺|瑚太朗",
	},
	key_tenzen: {
		sex: "male",
		group: "key",
		hp: 4,
		skills: ["tenzen_fenghuan", "tenzen_retianquan"],
		names: "加纳|天善",
	},
	key_kyouko: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["kyouko_rongzhu", "kyouko_gongmian"],
		names: "伊座并|杏子",
	},
	key_kyou: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["kyou_zhidian", "kyou_duanfa"],
		names: "藤林|杏",
	},
	key_seira: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["seira_xinghui", "seira_yuanying"],
		names: "樱庭|星罗",
	},
	key_kiyu: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["kiyu_yuling", "kiyu_rexianyu"],
		names: "天宫|希优",
	},
	key_tomoyo: {
		sex: "female",
		group: "key",
		hp: 4,
		skills: ["tomoyo_wuwei", "tomoyo_zhengfeng"],
		names: "坂上|智代",
	},
	key_minagi: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["minagi_peiquan", "minagi_huanliu"],
		names: "远野|美凪",
	},
	key_michiru: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["michiru_sheyuan"],
		names: "远野|小满",
	},
};

export default characters;
