const characters = {
    sp_key_yuri: ["female", "qun", 4, ["mubing", "ziqu", "diaoling"], ["border:key"]],
    key_lucia: ["female", "key", "2/3", ["lucia_duqu", "lucia_zhenren"]],
    key_kyousuke: ["male", "key", 4, ["nk_shekong", "key_huanjie"]],
    key_yuri: ["female", "key", 3, ["yuri_xingdong", "key_huanjie", "yuri_wangxi"], ["zhu"]],
    key_haruko: ["female", "key", 4, ["haruko_haofang", "haruko_zhuishi"]],
    key_umi: ["female", "key", 3, ["umi_chaofan", "umi_lunhui", "umi_qihuan"]],
    key_umi2: ["female", "key", 3, [], ["unseen"]],
    key_rei: ["male", "key", 4, ["xiandeng", "shulv", "xisheng"]],
    key_komari: ["female", "key", 3, ["komari_tiankou", "komari_xueshang"]],
    key_yukine: ["female", "key", 3, ["yukine_wenzhou"]],
    key_yusa: ["female", "key", 3, ["yusa_yanyi", "yusa_misa", "dualside"], ["dualside:key_misa"]],
    key_misa: ["female", "key", 3, ["misa_yehuo", "misa_yusa", "dualside"], ["unseen"]],
    key_masato: ["male", "key", "4/8", ["masato_baoquan"]],
    key_iwasawa: ["female", "key", 3, ["iwasawa_yinhang", "iwasawa_mysong"]],
    key_kengo: ["male", "key", 4, ["kengo_weishang", "kengo_guidui"]],
    key_yoshino: ["male", "key", 4, ["yoshino_jueyi"]],
    key_yui: ["female", "key", 3, ["yui_jiang", "yui_lieyin", "yui_takaramono"]],
    key_tsumugi: ["female", "key", 3, ["tsumugi_mugyu", "tsumugi_huilang"]],
    key_saya: ["female", "key", 3, ["saya_shouji", "saya_powei"]],
    key_harukakanata: ["female", "key", 3, ["haruka_shuangche"]],
    key_inari: ["female", "key", 2, ["inari_baiwei", "inari_huhun"]],
    key_shiina: ["female", "key", 3, ["shiina_qingshen", "shiina_feiyan"]],
    key_sunohara: [
        "double",
        "key",
        "3/3/2",
        ["sunohara_chengshuang", "sunohara_tiaoyin", "sunohara_jianren"],
    ],
    key_rin: ["female", "key", 3, ["rin_baoqiu"]],
    key_sasami: ["female", "key", 3, ["sasami_miaobian"]],
    key_akane: ["female", "key", 3, ["akane_jugu", "akane_quanqing", "akane_yifu"], ["zhu"]],
    key_doruji: ["female", "key", 16, ["doruji_feiqu"]],
    key_yuiko: ["female", "key", 3, ["yuiko_fenglun", "yuiko_dilve"]],
    key_riki: ["double", "key", 3, ["riki_spwenji", "riki_nvzhuang", "riki_mengzhong"]],
    key_hisako: ["female", "key", 3, ["hisako_yinbao", "hisako_zhuanyun"]],
    key_hinata: ["male", "key", 4, ["hinata_qiulve", "hinata_ehou"]],
    key_noda: ["male", "key", 4, ["noda_fengcheng", "noda_xunxin"]],
    key_tomoya: ["male", "key", 4, ["tomoya_shangxian", "tomoya_wangjin"]],
    key_nagisa: ["female", "key", 3, ["nagisa_tiandu", "nagisa_fuxin"]],
    key_ayato: ["male", "key", 3, ["ayato_jianshen", "ayato_zonghuan"]],
    key_ao: ["female", "key", 3, ["ao_xishi", "ao_kuihun", "ao_shixin"]],
    key_yuzuru: ["male", "key", 5, ["yuzuru_wuxin", "yuzuru_deyi"]],
    sp_key_kanade: ["female", "key", 3, ["kanade_mapo", "kanade_benzhan"]],
    key_mio: ["female", "key", 3, ["mio_tuifu", "mio_tishen"]],
    key_midori: ["female", "key", 3, ["midori_nonghuan", "midori_tishen"]],
    key_kyoko: ["female", "key", 3, ["kyoko_juwu", "kyoko_zhengyi"]],
    key_shizuru: ["female", "key", 3, ["shizuru_nianli", "shizuru_benzhan"]],
    key_shiorimiyuki: ["female", "key", 3, ["shiorimiyuki_banyin", "shiorimiyuki_tingxian"]],
    key_miki: ["female", "key", 3, ["miki_shenqiang", "miki_huanmeng", "miki_zhiluo"]],
    key_shiori: ["female", "key", "2/3", ["shiori_huijuan"]],
    key_kaori: ["female", "key", "3/4", ["kaori_siyuan"]],
    key_akiko: ["female", "key", 3, ["akiko_dongcha"]],
    key_abyusa: ["female", "key", 3, ["abyusa_jueqing", "abyusa_dunying"]],
    key_godan: ["male", "key", 6, ["godan_yuanyi", "godan_feiqu", "godan_xiaoyuan"]],
    key_yuu: ["male", "key", 3, ["yuu_lveduo"]],
    key_ryoichi: ["male", "key", 4, ["ryoichi_baoyi", "ryoichi_tuipi"]],
    key_kotori: ["female", "key", 3, ["kotori_yumo", "kotori_huazhan"]],
    key_jojiro: ["male", "key", 4, ["jojiro_shensu", "jojiro_shunying"]],
    key_shiroha: ["female", "key", 3, ["shiroha_yuzhao", "shiroha_guying", "shiroha_jiezhao"]],
    key_shizuku: ["female", "key", 3, ["shizuku_sizhi", "shizuku_biyi", "shizuku_sanhua"]],
    key_hiroto: ["male", "key", 3, ["hiroto_huyu", "hiroto_tuolao"]],
    key_sakuya: ["male", "key", 3, ["youlong", "luanfeng", "sakuya_junbu"]],
    key_youta: ["male", "key", 4, []],
    key_rumi: ["female", "key", "3/4", ["rumi_shuwu"]],
    key_chihaya: ["female", "key", 3, ["chihaya_liewu", "chihaya_youfeng"]],
    key_yukito: ["male", "key", 4, ["yukito_kongwu", "yukito_yaxiang"]],
    key_crow: ["male", "key", 4, [], ["unseen"]],
    key_asara: ["female", "key", 3, ["asara_shelu", "asara_yingwei"]],
    key_kotomi: ["female", "key", 3, ["kotomi_qinji", "kotomi_chuanxiang"]],
    key_mia: ["female", "key", 3, ["mia_shihui", "mia_qianmeng"]],
    key_kano: ["female", "key", 3, ["kano_liezhen", "kano_poyu"]],
    db_key_liyingxia: [
        "female",
        "shu",
        3,
        ["liyingxia_sanli", "liyingxia_zhenjun", "liyingxia_wumai"],
        ["doublegroup:shu:key"],
    ],
    key_erika: ["female", "key", "3/3/2", ["erika_shisong", "erika_yousheng"]],
    key_satomi: ["female", "key", 3, ["satomi_luodao", "satomi_daohai"]],
    key_iriya: ["female", "key", 3, ["iriya_yinji", "iriya_haozhi"]],
    key_fuuko: ["female", "key", 3, ["fuuko_xingdiao", "fuuko_chuanyuan"]],
};

export default characters;