const pinyins = {
	加藤うみ: ["Kato", "Umi"],
	仲村由理: ["Nakamura", "Yuri"],
	此花露西娅: ["Konohana", "Lucia"],
	枣恭介: ["Natsume", "Kyousuke"],
	神尾晴子: ["Kamio", "Haruko"],
	神北小毬: ["Kamikita", "Komari"],
	宫泽有纪宁: ["Miyazawa", "Yukine"],
	西森柚咲: ["Nishimori", "Yusa"],
	黑羽美砂: ["Kurobane", "Misa"],
	井之原真人: ["Inohara", "Masato"],
	岩泽雅美: ["Iwasawa", "Masami"],
	宫泽谦吾: ["Miyazawa", "Kengo"],
	吉野晴彦: ["Yoshino", "Haruhiko"],
	由依: ["Yui"],
	紬文德斯: ["Tsumugi", "Wenders"],
	朱鹭户沙耶: ["Tokido", "Saya"],
	"三枝叶留佳&二木佳奈多": ["Saigusa", "Haruka", "Futaki", "Kanata"],
	三枝二木: ["Saigusa", "Haruka", "Futaki", "Kanata"],
	稻荷: ["Inari"],
	椎名: ["Shiina"],
	"春原阳平&春原芽衣": ["Sunohara", "Youhei", "Sunohara", "Mei"],
	阳平芽衣: ["Sunohara", "Youhei", "Sunohara", "Mei"],
	枣铃: ["Natsume", "Rin"],
	笹濑川佐佐美: ["Sasasegawa", "Sasami"],
	千里朱音: ["Senri", "Akane"],
	多鲁基: ["Dorj"],
	来谷唯湖: ["Kurugaya", "Yuiko"],
	直枝理树: ["Naoe", "Riki"],
	渕田久子: ["Fuchita", "Hisako"],
	日向秀树: ["Hinata", "Hideki"],
	野田: ["Noda"],
	冈崎朋也: ["Okazaki", "Tomoya"],
	古河渚: ["Furukawa", "Nagisa"],
	直井文人: ["Naoi", "Ayato"],
	空门苍: ["Sorakado", "Ao"],
	音无结弦: ["Otonashi", "Yuzuru"],
	立华奏: ["Tachibana", "Kanade"],
	西园美鱼: ["Nishizono", "Mio"],
	西园美鸟: ["Nishizono", "Midori"],
	岬镜子: ["Misaki", "Kyoko"],
	中津静流: ["Nakatsu", "Shizuru"],
	"关根诗织&入江美雪": ["Sekine", "Shiori", "Irie", "Miyuki"],
	关根入江: ["Sekine", "Shiori", "Irie", "Miyuki"],
	野村美希: ["Nomura", "Miki"],
	美坂栞: ["Misaka", "Shiori"],
	美坂香里: ["Misaka", "Kaori"],
	水濑秋子: ["Minase", "Akiko"],
	游佐: ["Yusa"],
	松下护騨: ["Matsushita", "Godan"],
	乙坂有宇: ["Otosaka", "Yuu"],
	三谷良一: ["Mitani", "Ryoichi"],
	神户小鸟: ["Kanbe", "Kotori"],
	高城丈士朗: ["Takajyo", "Jyojirou"],
	鸣濑白羽: ["Naruse", "Shiroha"],
	水织静久: ["Mizuori", "Shizuku"],
	铃木央人: ["Suzuki", "Hiroto"],
	凤咲夜: ["Ootori", "Sakuya"],
	成神阳太: ["Narukami", "Youta"],
	七濑留美: ["Nanase", "Rumi"],
	凤千早: ["Ootori", "Chihaya"],
	国崎往人: ["Kunisaki", "Yukito"],
	井上晶: ["Inoue", "Asara"],
	一之濑琴美: ["Ichinose", "Kotomi"],
	藤川米娅: ["Fujikawa", "Mia"],
	雾岛佳乃: ["Kirishima", "Kano"],
	苍井绘梨花: ["Aoi", "Erika"],
	藏里见: ["Kura", "Satomi"],
	"喵呜·喵呼": ["Myau", "Mya-fu"],
	喵呜喵呼: ["Myau", "Mya-fu"],
	伊吹风子: ["Ibuki", "Fuuko"],
	久岛鸥: ["Kushima", "Kamome"],
	库特莉亚芙卡: ["Noumi", "Kudryavka"],
	神尾观铃: ["Kamio", "Misuzu"],
	友利奈绪: ["Tomori", "Nao"],
	天王寺瑚太朗: ["Tennouji", "Kotarou"],
	藤林杏: ["Fujibayashi", "Kyou"],
	伊座并杏子: ["Izanami", "Kyouko"],
	加纳天善: ["Kano", "Tenzen"],
	冰室忧希: ["Himuro", "Yuuki"],
	露娜Ｑ: ["Lunar", "Q"],
	远野小满: ["Toono", "Michiru"],
	远野美凪: ["Toono", "Minagi"],
	樱庭星罗: ["Sakuraba", "Seira"],
	坂上智代: ["Sakagami", "Tomoyo"],
	冈崎汐: ["Okazaki", "Ushio"],
	神山识: ["Kamiyama", "Shiki"],
	佐藤雏: ["Satou", "Hina"],
	篝: ["Kagari"],
};
export default pinyins;
