character.guozhan={
	character:{
		ganfuren:['female','shu',3,['shushen','shenzhi'],['fullskin']],
		mifuren:['female','shu',3,['guixiu','cunsi'],['fullskin']],
		mateng:['male','qun',4,['xiongyi','mashu'],['fullskin']],
		tianfeng:['male','qun',3,['sijian','suishi'],['fullskin']],
		yuejin:['male','wei',4,['xiaoguo'],['fullskin']],
		chendong:['male','wu',4,['duanxie','fenming'],['fullskin']],
		sp_dongzhuo:['male','qun',5,['hengzheng'],['fullskin']],
		jiangfei:['male','shu',3,['shengxi','shoucheng'],['fullskin']],
		jiangqing:['male','wu',4,['shangyi'],['fullskin']],
		hetaihou:['female','qun',3,['zhendu','qiluan'],['fullskin']],
		kongrong:['male','qun',3,['lirang','mingshi'],['fullskin']],
		dingfeng:['male','wu',4,['fenxun'],['fullskin']],
	},
};
