character.guozhan={
	connect:true,
	character:{
		ganfuren:['female','shu',3,['shushen','shenzhi']],
		mifuren:['female','shu',3,['guixiu','cunsi']],
		mateng:['male','qun',4,['xiongyi','mashu']],
		tianfeng:['male','qun',3,['sijian','suishi']],
		yuejin:['male','wei',4,['xiaoguo']],
		chendong:['male','wu',4,['duanxie','fenming']],
		sp_dongzhuo:['male','qun',5,['hengzheng']],
		jiangfei:['male','shu',3,['shengxi','shoucheng']],
		jiangqing:['male','wu',4,['shangyi']],
		hetaihou:['female','qun',3,['zhendu','qiluan']],
		kongrong:['male','qun',3,['lirang','mingshi']],
		dingfeng:['male','wu',4,['fenxun']],
		panfeng:['male','qun',4,['kuangfu']],
	},
};
