character.xswd={
	character:{
		// swd_wushi:['male','wei',3,['zhoufu','yingbin','xuying']],
			// swd_lanmoshen:['female','wei',3,['bingjian','lieren']],
			swd_huanglei:['male','qun',3,['jilve','gongshen']],
		// swd_libai:['female','qun',3,['miaobi','zhexian']],
		// swd_kendi:['male','qun',3,['guanxing','jianyan']],
		// swd_lijing:['male','qun',4,['tianyi','zhuhai']],
		// swd_lilian:['female','qun',3,['swd_wuxie','qingcheng']],
		// swd_linming:['male','qun',3,['shelie','bifa']],
		// swd_philis:['male','qun',4,['yicong','wangxi']],
		// swd_pepin:['male','qun',4,['rejianxiong','quhu']],
			swd_kangnalishi:['male','qun',1,['busi','xuying','yinguo']],
			swd_xuanyuanjiantong:['male','qun',3,['chengjian','huanling']],
		// swd_huiyan:['male','qun',3,['wendao','xiaozhan','xunzhi']],

		// swd_chenfu:['male','qun',4,['xuanzhou','bingfeng']],
		// swd_chengyaojin:['male','qun',4,['jiuchi','jufu']],
			swd_shanxiaoxiao:['female','wu',3,['shehun','xiaomoyu']],
			swd_yuchiyanhong:['female','shu',3,['huanxing','meihuo']],
		// swd_hanteng:['male','qun',4,['kuangfu']],
		// swd_heran:['male','qun',3,['yujian','guiyin','shejie']],
		// swd_xingtian:['male','qun',8,[]],
		// swd_qinshubao:['male','qun',3,['huajing','pingxu']],
		// swd_tuobayueer:['female','shu',3,['shushen','biyue']],
		// swd_yangshuo:['male','qun',4,['longdan','luomu']],
		// swd_zhanglie:['male','qun',4,['huajin','poxiao']],


			swd_hanluo:['male','qun',5,['hzhenwei']],
			swd_fu:['male','qun',5,['yudun','paoxiao']],
			swd_linyue:['male','wei',3,['zhenjiu','mazui']],
			swd_zidashu:['male','wu',3,['shoulie','hudun']],
			swd_maixing:['male','wu',3,['toudan','shending']],
			swd_fuyan:['male','qun',4,['lianda']],
			swd_haidapang:['female','wu',3,['bingjian','rumeng']],
			swd_shaowei:['female','shu',3,['jianji','huangyu']],

			swd_youzhao:['male','shu',4,['longdan','yuchen']],
		// swd_qingming:['male','shu',3,['mingfu','tianlun']],
			swd_shangzhang:['male','shu',4,['lianwu']],
			swd_situqiang:['female','shu',3,['qingnang','chulao']],

			swd_chunyuheng:['male','wei',2,['jueqing','shengshou','xuying']],
			swd_hanlong:['male','wei',4,['ciqiu','siji']],
			swd_yuli:['female','wu',3,['lingxin','tianxiang']],
			swd_zhanggao:['male','wei',4,['yicong','poxing']],

			swd_hupo:['male','wu',3,['dunxing','guiying']],
			swd_jiangziya:['male','wu',3,['mingfu','tianlun']],
	},
}
