const characterReplaces = {
	yuejin: ["yuejin", "std_yuejin"],
	chenlin: ["chenlin", "dc_sb_chenlin"],
	shamoke: ["shamoke", "ty_shamoke"],
	guanyinping: ["guanyinping", "old_guanyinping", "ty_guanyinping"],
	shixie: ["shixie", "dc_shixie", "old_shixie"],
	caoshuang: ["caoshuang", "dc_caoshuang", "ns_caoshuang"],
	caoang: ["caoang", "yj_caoang", "tw_caoang"],
	caohong: ["caohong", "tw_re_caohong", "tw_caohong", "yj_caohong"],
	xiahouba: ["xiahouba", "dc_xiahouba", "tw_xiahouba", "std_xiahouba"],
	maliang: ["maliang", "re_maliang", "tw_maliang", "ol_maliang", "old_maliang", "std_maliang"],
	dingfeng: ["dingfeng", "tw_dingfeng", "old_dingfeng", "std_dingfeng"],
	zumao: ["zumao", "tw_zumao"],
	tw_beimihu: ["beimihu", "tw_beimihu"],
	panfeng: ["panfeng", "re_panfeng", "std_panfeng"],
	sunluyu: ["sunluyu", "re_sunluyu", "mb_sunluyu"],
	jin_simazhao: ["jin_simazhao", "simazhao", "sp_simazhao", "jd_jin_simazhao", "jsrg_simazhao", "jin_jsrg_simazhao"],
	jin_wangyuanji: ["jin_wangyuanji", "wangyuanji", "sp_wangyuanji", "std_wangyuanji", "jd_jin_wangyuanji"],
	wangyun: ["clan_wangyun", "wangyun", "dc_wangyun", "re_wangyun", "jsrg_wangyun", "old_wangyun", "pe_wangyun", "std_wangyun"],
	zhangliang: ["xin_zhangliang", "re_zhangliang", "zhangliang"],
	lingju: ["lingju", "old_lingju"],
	guansuo: ["guansuo", "dc_guansuo", "std_guansuo"],
	zhangxingcai: ["zhangxingcai", "old_zhangxingcai"],
	lisu: ["ol_lisu", "lisu"],
	fuwan: ["fuwan", "tw_fuwan", "sp_fuwan"],
	huaxin: ["ol_huaxin", "huaxin", "sp_huaxin", "std_huaxin", "jd_ol_huaxin"],
	xujing: ["xujing", "dc_xujing", "sp_xujing", "tw_xujing"],
	zhaoxiang: ["zhaoxiang", "dc_zhaoxiang", "tw_zhaoxiang"],
	dengzhi: ["ol_dengzhi", "re_dengzhi", "dengzhi", "tw_dengzhi", "std_re_dengzhi"],
	wangrong: ["ol_wangrong", "wangrong"],
	zongyu: ["zongyu", "sp_zongyu", "tw_zongyu"],
	ol_dongzhao: ["ol_dongzhao", "dc_dongzhao", "tw_dongzhao"],
	mayunlu: ["mayunlu", "tw_mayunlu", "std_mayunlu"],
	zhuling: ["ol_zhuling", "dc_zhuling", "zhuling"],
	zangba: ["zangba", "tw_zangba"],
	zhangbao: ["zhangbao", "re_zhangbao"],
	jianggan: ["jianggan", "sp_jianggan", "std_jianggan"],
	dc_jiben: ["dc_jiben", "sp_jiben"],
	yangyi: ["ol_yangyi", "yangyi", "tw_yangyi"],
	tianyu: ["tianyu", "tw_tianyu"],
	huangchengyan: ["huangchengyan", "dc_huangchengyan"],
	puyuan: ["ol_puyuan", "puyuan"],
	huangzu: ["huangzu", "dc_huangzu"],
	huojun: ["huojun", "dc_huojun", "xin_huojun", "tw_huojun"],
	zhaoyǎn: ["zhaoyǎn", "dc_zhaoyǎn"],
	furong: ["ol_furong", "furong", "tw_furong"],
	daxiaoqiao: ["daxiaoqiao", "dc_daxiaoqiao", "tw_daxiaoqiao"],
	zhugeguo: ["zhugeguo", "tw_zhugeguo", "yue_zhugeguo", "huan_zhugeguo"],
	wanglang: ["ol_wanglang", "wanglang", "old_wanglang", "std_wanglang"],
	tengfanglan: ["tengfanglan", "dc_tengfanglan"],
	zhangyì: ["ol_zhangyì", "zhangyì", "std_zhangyì"],
	yuantanyuanshang: ["yuantanyuanshang", "yuantanyuanxiyuanshang"],
	ruiji: ["ruiji", "dc_ruiji"],
	jsp_huangyueying: ["jsp_huangyueying", "re_jsp_huangyueying"],
	ganfuren: ["ganfuren", "dc_ganfuren", "jsp_ganfuren"],
	zhouqun: ["ol_zhouqun", "zhouqun"],
	qianzhao: ["ol_qianzhao", "qianzhao"],
	ol_pengyang: ["ol_pengyang", "sp_pengyang", "std_pengyang"],
	ol_luyusheng: ["ol_luyusheng", "luyusheng"],
	fanjiangzhangda: ["fanjiangzhangda", "jsrg_fanjiangzhangda"],
	simalang: ["re_simalang", "simalang"],
	zhugedan: ["re_zhugedan", "zhugedan", "jsrg_zhugedan"],
	jsrg_zhangren: ["jsrg_zhangren", "dc_zhangren"],
	ol_wenqin: ["ol_wenqin", "pe_wenqin", "mb_wenqin"],
	lukai: ["ol_lukai", "lukai"],
	liupi: ["ol_liupi", "liupi"],
	kanze: ["kanze", "re_kanze"],
	lvfan: ["lvfan", "sp_lvfan", "std_lvfan"],
	dongbai: ["dongbai", "re_dongbai", "jsrg_dongbai"],
	sp_jiaxu: ["dc_sp_jiaxu", "yj_jiaxu", "sp_jiaxu"],
	duji: ["duji", "re_duji", "ns_duji"],
	sp_taishici: ["sp_taishici", "re_sp_taishici"],
	mazhong: ["mazhong", "re_mazhong", "tw_mazhong"],
	wenpin: ["wenpin", "re_wenpin"],
	liuyan: ["liuyan", "jsrg_liuyan", "junk_liuyan"],
	buzhi: ["buzhi", "ty_buzhi"],
};

export default characterReplaces;
