export default {
	yuejin: ["re_lidian"],
	zhugejin: ["zhugeke", "sunquan"],
	guanyinping: ["guanyu"],
	zhangxingcai: ["liushan"],
	fuwan: ["fuhuanghou"],
	sunshangxiang: ["liubei"],
	caoang: ["caocao"],
	zhangbao: ["zhangliang", "zhangjiao"],
	zhangliang: ["zhangjiao"],
	maliang: ["masu"],
	lingcao: ["lingtong"],
	lingju: ["diaochan", "lvbu"],
	jiangqing: ["zhoutai"],
	dingfeng: ["xusheng", "zhugeke"],
	caohong: ["caoren"],
	daxiaoqiao: ["zhouyu", "sunce"],
	cuiyan: ["caocao"],
	guansuo: ["guanyu"],
	mateng: ["machao", "madai", "mayunlu"],
	chengpu: ["zhouyu"],
	hanba: ["swd_muyun"],
	dongbai: ["dongzhuo"],
	cuimao: ["caopi"],
	simazhao: ["wangyuanji"],
};
