export default {
	yuejin: ["re_lidian"],
	zhugejin: ["zhugeke", "sunquan"],
	guanyinping: ["guanyu"],
	zhangxingcai: ["liushan"],
	fuwan: ["fuhuanghou"],
	sunshangxiang: ["liubei"],
	caoang: ["caocao"],
	zhangbao: ["zhangliang", "zhangjiao"],
	zhangliang: ["zhangjiao"],
	maliang: ["masu"],
	lingcao: ["lingtong"],
	lingju: ["diaochan", "lvbu"],
	jiangqing: ["zhoutai"],
	dingfeng: ["xusheng", "re_xusheng", "zhugeke"],
	caohong: ["caoren"],
	daxiaoqiao: ["zhouyu", "sunce"],
	cuiyan: ["caocao"],
	guansuo: ["guanyu"],
	mateng: ["machao", "madai", "mayunlu"],
	chengpu: ["zhouyu"],
	hanba: ["swd_muyun"],
	cuimao: ["caopi"],
	simazhao: ["wangyuanji"],
	lijue: ["guosi", "jiaxu"],
	zhangji: ["zhangxiu", "drlt_zhangxiu", "zoushi"],
	xf_sufei: ["ganning"],
	simahui: ["pangdegong"],
	zhangqiying: ["zhanglu"],
	pangtong: ["zhugejin"],
	taishici: ["liuyao", "kongrong"],
};
