const characters = {
	old_re_lidian: ["male", "wei", 3, ["xunxun", "wangxi"], ["die:lidian"]],
	ganfuren: ["female", "shu", 3, ["stdshushen", "shenzhi"], ["name:甘|null"]],
	std_panfeng: ["male", "qun", 4, ["stdkuangfu"]],
	caocao: ["male", "wei", 4, ["jianxiong", "hujia"], ["zhu"]],
	simayi: ["male", "wei", 3, ["fankui", "guicai"], ["name:司马|懿"]],
	xiahoudun: ["male", "wei", 4, ["ganglie"], ["name:夏侯|惇"]],
	zhangliao: ["male", "wei", 4, ["tuxi"]],
	xuzhu: ["male", "wei", 4, ["luoyi"]],
	guojia: ["male", "wei", 3, ["tiandu", "yiji"]],
	zhenji: ["female", "wei", 3, ["luoshen", "qingguo"]],
	liubei: ["male", "shu", 4, ["rende", "jijiang"], ["zhu"]],
	guanyu: ["male", "shu", 4, ["wusheng"]],
	zhangfei: ["male", "shu", 4, ["paoxiao"]],
	zhugeliang: ["male", "shu", 3, ["guanxing", "kongcheng"], ["name:诸葛|亮"]],
	zhaoyun: ["male", "shu", 4, ["longdan"]],
	machao: ["male", "shu", 4, ["mashu", "tieji"]],
	huangyueying: ["female", "shu", 3, ["jizhi", "qicai"]],
	sunquan: ["male", "wu", 4, ["zhiheng", "jiuyuan"], ["zhu"]],
	ganning: ["male", "wu", 4, ["qixi"]],
	lvmeng: ["male", "wu", 4, ["keji"]],
	huanggai: ["male", "wu", 4, ["kurou"]],
	zhouyu: ["male", "wu", 3, ["yingzi", "fanjian"]],
	daqiao: ["female", "wu", 3, ["guose", "liuli"], ["name:桥|null"]],
	luxun: ["male", "wu", 3, ["qianxun", "lianying"]],
	sunshangxiang: ["female", "wu", 3, ["xiaoji", "jieyin"]],
	huatuo: ["male", "qun", 3, ["qingnang", "jijiu"]],
	lvbu: ["male", "qun", 4, ["wushuang"]],
	diaochan: ["female", "qun", 3, ["lijian", "biyue"], ["name:null|null"]],
	huaxiong: ["male", "qun", 6, ["yaowu"]],
	gongsunzan: ["male", "qun", 4, ["reyicong"], ["name:公孙|瓒"]],

	xf_yiji: ["male", "shu", 3, ["xinfu_jijie", "xinfu_jiyuan"], []],
	re_yuanshu: ["male", "qun", 4, ["rewangzun", "retongji"]],

	std_sunhao: ["male", "wu", 5, ["stdcanshi", "chouhai", "guiming"], ["zhu"]],
	std_mateng: ["male", "qun", 4, ["stdxiongyi", "mashu", "stdyouji"], ["zhu"]],
	std_mayunlu: ["female", "shu", 4, ["stdfengpo", "mashu"]],
	std_jianggan: ["male", "wei", 3, ["stddaoshu", "stddaizui"]],
	std_zhouchu: ["male", "wu", 4, ["stdxiongxia"]],
	std_lvlingqi: ["female", "qun", 4, ["stdhuizhan"]],
	std_dc_yanghu: ["male", "wei", 4, ["stdmingfa"]],
	std_dc_luotong: ["male", "wu", 3, ["stdjinjian", "stdrenzheng"]],
	std_lijue: ["male", "qun", 5, ["stdxiongsuan"]],
	std_chengpu: ["male", "wu", 4, ["stdchunlao"]],
	std_db_wenyang: ["male", "wei", 4, ["stdquedi"]],
	std_re_dengzhi: ["male", "shu", 3, ["stdzhiyinmeng", "stdhehe"]],
	std_zhangyì: ["male", "shu", 4, ["stdzhiyi"]],
	std_chengyu: ["male", "wei", 3, ["stdshefu", "stdyibing"]],
	std_fanyufeng: ["female", "qun", 3, ["stdbazhan", "stdzhanying"]],
	std_feiyi: ["male", "shu", 3, ["stdtiaohe", "stdqiansu"]],
};

export default characters;
