const characterReplaces = {
	caocao: ["caocao", "re_caocao", "sb_caocao", "dc_caocao"],
	guojia: ["guojia", "re_guojia", "ps1059_guojia", "ps2070_guojia"],
	simayi: ["simayi", "re_simayi", "jsrg_simayi", "ps_simayi", "ps2068_simayi"],
	jin_simayi: ["jin_simayi", "junk_simayi", "ps_jin_simayi"],
	zhenji: ["zhenji", "re_zhenji", "sb_zhenji", "yj_zhenji"],
	xuzhu: ["xuzhu", "re_xuzhu"],
	zhangliao: ["zhangliao", "re_zhangliao"],
	sp_zhangliao: ["sp_zhangliao", "yj_zhangliao", "jsrg_zhangliao"],
	xiahoudun: ["xiahoudun", "re_xiahoudun", "xin_xiahoudun", "sb_xiahoudun"],
	liubei: ["liubei", "re_liubei", "sb_liubei", "dc_liubei", "junk_liubei"],
	guanyu: ["guanyu", "re_guanyu", "ol_sb_guanyu", "sb_guanyu", "ps_guanyu", "old_guanyu", "junk_guanyu"],
	zhangfei: ["zhangfei", "re_zhangfei", "old_zhangfei", "xin_zhangfei", "sb_zhangfei", "tw_zhangfei", "jsrg_zhangfei", "yj_zhangfei"],
	zhaoyun: ["zhaoyun", "re_zhaoyun", "old_zhaoyun", "sb_zhaoyun", "jsrg_zhaoyun", "ps2063_zhaoyun", "ps2067_zhaoyun"],
	sp_zhaoyun: ["sp_zhaoyun", "jsp_zhaoyun"],
	machao: ["machao", "re_machao", "sb_machao", "ps_machao"],
	sp_machao: ["sp_machao", "dc_sp_machao", "jsrg_machao", "old_machao"],
	zhugeliang: ["zhugeliang", "re_zhugeliang", "sb_zhugeliang", "ps2066_zhugeliang", "ps_zhugeliang"],
	huangyueying: ["huangyueying", "re_huangyueying", "junk_huangyueying", "sb_huangyueying"],
	sunquan: ["sunquan", "re_sunquan", "sb_sunquan", "dc_sunquan"],
	zhouyu: ["zhouyu", "re_zhouyu", "dc_sb_zhouyu", "sb_zhouyu", "ps1062_zhouyu", "ps2080_zhouyu"],
	luxun: ["luxun", "re_luxun", "jsrg_luxun"],
	lvmeng: ["lvmeng", "re_lvmeng", "sb_lvmeng"],
	huanggai: ["huanggai", "re_huanggai", "sb_huanggai"],
	daqiao: ["daqiao", "re_daqiao", "sb_daqiao"],
	sunshangxiang: ["sunshangxiang", "re_sunshangxiang", "sb_sunshangxiang", "jsrg_sunshangxiang"],
	ganning: ["ganning", "re_ganning", "sb_ganning", "yongjian_ganning"],
	yj_ganning: ["yj_ganning", "sp_ganning"],
	lvbu: ["lvbu", "re_lvbu", "jsrg_lvbu", "ps_lvbu"],
	diaochan: ["diaochan", "re_diaochan", "sb_diaochan"],
	huatuo: ["huatuo", "re_huatuo", "old_huatuo"],
	huaxiong: ["huaxiong", "re_huaxiong", "old_huaxiong", "sb_huaxiong", "ol_huaxiong"],
	yuanshu: ["yuanshu", "re_yuanshu", "yl_yuanshu", "old_yuanshu", "ol_yuanshu", "star_yuanshu"],
	gongsunzan: ["gongsunzan", "re_gongsunzan", "dc_gongsunzan", "xin_gongsunzan"],
	re_lidian: ["re_lidian", "old_re_lidian", "junk_lidian"],
};

export default characterReplaces;
