const characterReplaces = {
	caocao: ["caocao", "re_caocao", "sb_caocao", "dc_caocao", "jd_sb_caocao", "jsrg_caocao"],
	guojia: ["guojia", "re_guojia", "yj_sb_guojia", "ps1059_guojia", "ps2070_guojia", "jsrg_guojia"],
	simayi: ["simayi", "re_simayi", "dc_sb_simayi", "jsrg_simayi", "ps_simayi", "ps2068_simayi", "yy_simayi"],
	jin_simayi: ["jin_simayi", "junk_simayi", "huan_simayi", "ps_jin_simayi"],
	zhenji: ["zhenji", "re_zhenji", "sb_zhenji", "yj_zhenji"],
	xuzhu: ["xuzhu", "re_xuzhu"],
	zhangliao: ["zhangliao", "re_zhangliao"],
	sp_zhangliao: ["sp_zhangliao", "yj_zhangliao", "jsrg_zhangliao"],
	xiahoudun: ["xiahoudun", "re_xiahoudun", "xin_xiahoudun", "sb_xiahoudun", "xia_xiahoudun", "sp_xiahoudun"],
	liubei: ["liubei", "re_liubei", "sb_liubei", "dc_liubei", "junk_liubei", "jd_sb_liubei", "ty_liubei", "xia_liubei", "sp_liubei", "jsrg_liubei"],
	guanyu: ["guanyu", "re_guanyu", "ol_sb_guanyu", "sb_guanyu", "ps_guanyu", "old_guanyu", "junk_guanyu", "wuhujiang", "jx_guanyu", "jd_sb_guanyu", "ty_guanyu", "xia_guanyu", "drag_guanyu"],
	zhangfei: ["zhangfei", "re_zhangfei", "old_zhangfei", "xin_zhangfei", "sb_zhangfei", "tw_zhangfei", "jsrg_zhangfei", "yj_zhangfei", "wuhujiang", "jd_sb_zhangfei", "sp_zhangfei"],
	zhaoyun: ["zhaoyun", "re_zhaoyun", "old_zhaoyun", "sb_zhaoyun", "jsrg_zhaoyun", "ps2063_zhaoyun", "ps2067_zhaoyun", "huan_zhaoyun", "wuhujiang", "jd_sb_zhaoyun"],
	sp_zhaoyun: ["sp_zhaoyun", "jsp_zhaoyun", "yy_zhaoyun"],
	machao: ["machao", "re_machao", "sb_machao", "ps_machao", "wuhujiang"],
	sp_machao: ["sp_machao", "dc_sp_machao", "jsrg_machao", "old_machao"],
	zhugeliang: ["zhugeliang", "re_zhugeliang", "ps2066_zhugeliang", "ps_zhugeliang", "huan_zhugeliang", "jsrg_zhugeliang"],
	huangyueying: ["huangyueying", "re_huangyueying", "junk_huangyueying", "sb_huangyueying", "jd_sb_huangyueying"],
	sunquan: ["sunquan", "re_sunquan", "sb_sunquan", "dc_sunquan", "xin_sunquan", "jd_sb_sunquan", "ty_sunquan"],
	zhouyu: ["zhouyu", "re_zhouyu", "dc_sb_zhouyu", "sb_zhouyu", "ps1062_zhouyu", "ps2080_zhouyu", "jx_zhouyu"],
	luxun: ["luxun", "re_luxun", "jsrg_luxun", "sb_luxun", "ty_luxun", "huan_luxun"],
	lvmeng: ["lvmeng", "re_lvmeng", "sb_lvmeng", "sp_lvmeng"],
	huanggai: ["huanggai", "re_huanggai", "sb_huanggai", "dc_sb_huanggai"],
	daqiao: ["daqiao", "re_daqiao", "sb_daqiao", "jd_sb_daqiao", "yue_daqiao", "sp_daqiao"],
	sunshangxiang: ["sunshangxiang", "re_sunshangxiang", "jsrg_sunshangxiang", "star_sunshangxiang", "sp_sunshangxiang", "sb_sunshangxiang", "jd_sb_sunshangxiang"],
	ganning: ["ganning", "re_ganning", "sb_ganning", "yongjian_ganning", "jd_sb_ganning", "ty_ganning"],
	yj_ganning: ["yj_ganning", "sp_ganning"],
	lvbu: ["lvbu", "re_lvbu", "jsrg_lvbu", "ps_lvbu"],
	diaochan: ["diaochan", "re_diaochan", "sb_diaochan", "sp_diaochan", "yue_diaochan"],
	huatuo: ["huatuo", "re_huatuo", "old_huatuo"],
	huaxiong: ["huaxiong", "re_huaxiong", "old_huaxiong", "sb_huaxiong", "ol_huaxiong", "ol_sb_huaxiong"],
	yuanshu: ["yuanshu", "re_yuanshu", "yl_yuanshu", "old_yuanshu", "ol_yuanshu", "star_yuanshu"],
	gongsunzan: ["gongsunzan", "re_gongsunzan", "dc_gongsunzan", "xin_gongsunzan", "sb_gongsunzan", "sp_gongsunzan", "yy_gongsunzan"],
	re_lidian: ["re_lidian", "old_re_lidian", "junk_lidian"],
};

export default characterReplaces;
