const characters = {
	junk_zhangjiao: ["male", "shen", 3, ["yizhao", "junksijun", "tianjie"], ["qun", "die:shen_zhangjiao"]],
	junk_sunquan: ["male", "shen", 4, ["dili", "yuheng"], ["wu", "die:shen_sunquan"]],
	shen_huangzhong: ["male", "shen", 4, ["new_dclieqiong", "dczhanjue"], ["shu"]],
	new_simayi: ["male", "shen", 4, ["jilin", "yingyou", "yingtian"], ["wei", "name:司马|懿"]],
	xin_simayi: ["male", "shen", 4, ["xinrenjie", "xinbaiyin", "xinlianpo"], ["tempname:new_simayi", "wei", "name:司马|懿", "die:new_simayi"]],
	dc_shen_huatuo: ["male", "shen", 3, ["jingyu", "lvxin", "huandao"], ["qun"]],
	shen_xuzhu: ["male", "shen", 5, ["zhengqing", "zhuangpo"], ["wei"]],
	shen_lusu: ["male", "shen", 3, ["tamo", "dingzhou", "zhimeng"], ["wu"]],
	shen_huatuo: ["male", "shen", 3, ["wuling", "youyi"], ["qun"]],
	le_shen_jiaxu: ["male", "shen", 4, ["jxlianpo", "jxzhaoluan"], ["qun"]],
	shen_dianwei: ["male", "shen", 4, ["juanjia", "qiexie", "cuijue"], ["wei"]],
	shen_dengai: ["male", "shen", 4, ["dctuoyu", "dcxianjin", "dcqijing"], ["wei"]],
	tw_shen_lvmeng: ["male", "shen", 3, ["twshelie", "twgongxin"], ["wu"]],
	shen_zhangjiao: ["male", "shen", 3, ["yizhao", "sijun", "sanshou", "tianjie"], ["qun"]],
	shen_zhangfei: ["male", "shen", 4, ["shencai", "xunshi"], ["shu"]],
	tw_shen_guanyu: ["male", "shen", 4, ["twwushen", "twwuhun"], ["shu"]],
	shen_machao: ["male", "shen", 4, ["shouli", "hengwu"], ["shu"]],
	shen_sunquan: ["male", "shen", 4, ["junkyuheng", "junkdili"], ["wu"]],
	shen_jiangwei: ["male", "shen", 4, ["jiufa", "tianren", "pingxiang"], ["shu"]],

	shen_sunce: ["male", "shen", "1/6", ["yingba", "scfuhai", "pinghe"], ["wu"]],
	shen_xunyu: ["male", "shen", 3, ["tianzuo", "lingce", "dinghan"], ["wei", "clan:颍川荀氏"]],
	shen_taishici: ["male", "shen", 4, ["dulie", "tspowei"], ["wu", "name:太史|慈"]],
	shen_guojia: ["male", "shen", 3, ["reshuishi", "stianyi", "resghuishi"], ["wei"]],
	shen_diaochan: ["female", "shen", 3, ["meihun", "huoxin"], ["qun", "name:null|null"]],
	shen_guanyu: ["male", "shen", 5, ["wushen", "new_wuhun"], ["shu"]],
	shen_zhaoyun: ["male", "shen", 2, ["xinjuejing", "relonghun"], ["shu"]],
	shen_zhugeliang: ["male", "shen", 3, ["qixing", "kuangfeng", "dawu"], ["shu", "name:诸葛|亮"]],
	shen_lvmeng: ["male", "shen", 3, ["shelie", "gongxin"], ["wu"]],
	shen_zhouyu: ["male", "shen", 4, ["yeyan", "qinyin"], ["wu"]],
	shen_simayi: ["male", "shen", 4, ["renjie", "sbaiyin", "lianpo"], ["wei", "name:司马|懿"]],
	shen_caocao: ["male", "shen", 3, ["new_guixin", "feiying"], ["wei"]],
	shen_lvbu: ["male", "shen", 5, ["baonu", "wumou", "ol_wuqian", "ol_shenfen"], ["qun"]],

	shen_liubei: ["male", "shen", 6, ["nzry_longnu", "nzry_jieying"], ["shu"]],
	shen_luxun: ["male", "shen", 4, ["nzry_junlve", "nzry_cuike", "nzry_dinghuo"], ["wu"]],
	shen_zhangliao: ["male", "shen", 4, ["drlt_duorui", "drlt_zhiti"], ["wei"]],
	shen_ganning: ["male", "shen", "3/6", ["drlt_poxi", "drlt_jieying"], ["wu"]],
	ol_zhangliao: ["male", "shen", 4, ["olduorui", "olzhiti"], ["wei", "die:shen_zhangliao"]],
	shen_caopi: ["male", "shen", 5, ["chuyuan", "dengji"], ["wei"]],
	shen_zhenji: ["female", "shen", 3, ["shenfu", "qixian"], ["wei"]],
	boss_zhaoyun: ["male", "shen", 1, ["boss_juejing", "xinlonghun", "zhanjiang"], ["shu"]],
};

export default characters;
