const characters = {
	mb_sp_zhenji: ["female", "qun", 3, ["mbbojian", "mbjiwei"]],
	mb_zhangfen: ["male", "wu", 4, ["mbquchong", "mbxunjie"]],
	mb_jiachong: ["male", "qun", 3, ["mbbeini", "mbdingfa"], ["border:jin", "die:jiachong"]],
	mb_simazhou: ["male", "wei", 4, ["mbbifeng", "mbsuwang"], ["name:司马|伷", "border:jin"]],
	mb_wenqin: ["male", "wei", 4, ["mbbeiming", "mbchoumang"]],
	mb_simafu: ["male", "wei", 3, ["mbpanxiang", "mbchenjie"], ["name:司马|孚", "border:jin"]],
	mb_sp_guanqiujian: ["male", "wei", 4, ["mbcuizhen", "mbkuili"], ["name:毌丘|俭"]],
	mb_caomao: ["male", "wei", 3, ["mbqianlong", "mbweitong"], ["zhu"]],
	chengji: ["male", "wei", 4, ["mbkuangli", "mbxiongsi"], ["border:jin"]],
	lizhaojiaobo: ["male", "wei", 4, ["mbzuoyou", "mbshishou"], ["name:李|昭-焦|伯"]],
	yangfeng: ["male", "qun", 4, ["mbxuetu", "mbweiming"]],
	xin_huojun: ["male", "shu", 4, ["sidai", "jieyu"], ["character:tw_huojun", "die:tw_huojun"]],
	muludawang: ["male", "qun", "3/3/1", ["shoufa", "zhoulin", "yuxiang"], ["name:null|null"]],
	mb_chengui: ["male", "qun", 3, ["guimou", "zhouxian"]],
	mb_huban: ["male", "wei", 4, ["mbyilie"]],
	mb_xianglang: ["male", "shu", 3, ["naxue", "yijie"]],
	yanxiang: ["male", "qun", 3, ["kujian", "ruilian"], ["die:tw_yanxiang"]],
	mb_sunluyu: ["female", "wu", 3, ["mbmeibu", "mbmumu"], ["die:sunluyu"]],
	xin_wuban: ["male", "shu", 4, ["xinjintao"], ["clan:陈留吴氏", "character:wuban", "die:wuban"]],
	baoxin: ["male", "qun", 4, ["mutao", "yimou"], ["die:tw_baoxin"]],
	jiangji: ["male", "wei", 3, ["twjichou", "jilun"], ["character:tw_jiangji", "die:tw_jiangji"]],
	liwei: ["male", "shu", 4, ["jiaohua"], ["die:tw_liwei"]],
	laimin: ["male", "shu", 3, ["laishou", "luanqun"]],
	xin_guozhao: ["female", "wei", 3, ["yichong", "wufei"]],
	xin_zhangyi: ["male", "shu", 4, ["xinwurong", "shizhi"]],
	xin_sunliang: ["male", "wu", 3, ["xinzhizheng", "xinkuizhu", "xinlijun"], ["zhu", "die:sunliang"]],
	re_xiaoqiao: ["female", "wu", 3, ["retianxiang", "xinhongyan"], ["name:桥|null"]],
	shichangshi: ["male", "qun", 1, ["mbdanggu", "mbmowang"], ["sex:male_castrated", "name:张|让-赵|忠-孙|璋-毕|岚-夏|恽-韩|悝-栗|嵩-段|珪-郭|胜-高|望"]],
	re_zhangzhang: ["male", "wu", 3, ["rezhijian", "guzheng"], ["name:张|昭-张|纮"]],
	qianzhao: ["male", "wei", 4, ["mbshihe", "mbzhenfu"]],
	re_yanwen: ["male", "qun", 4, ["reshuangxiong"], ["name:颜|良-文|丑"]],
	xin_zhoutai: ["male", "wu", 4, ["buqu", "new_fenji"], ["die:zhoutai"]],
	re_caozhi: ["male", "wei", 3, ["reluoying", "rejiushi", "chengzhang"]],
	re_chenqun: ["male", "wei", 3, ["redingpin", "refaen"]],
	xin_caoxiu: ["male", "wei", 4, ["qianju", "xinqingxi"]],
	xin_zhuhuan: ["male", "wu", 4, ["fenli", "xinpingkou"]],
	sp_pengyang: ["male", "shu", 3, ["spdaming", "spxiaoni"]],
	wangjun: ["male", "qun", 4, ["zhujian", "duansuo"], ["border:jin"]],
	xin_zhuzhi: ["male", "wu", 4, ["sbanguo"]],
	xin_wuyi: ["male", "shu", 4, ["sbbenxi"]],
	yangfu: ["male", "wei", 3, ["jiebing", "hannan"]],
	sp_caosong: ["male", "wei", 3, ["yijin", "guanzong"]],
	re_liru: ["male", "qun", 3, ["rejuece", "remieji", "xinfencheng"]],
	re_dianwei: ["male", "wei", 4, ["reqiangxi"]],
	xin_mamidi: ["male", "qun", 3, ["chengye", "buxu"]],
	ruanhui: ["female", "wei", 3, ["mingcha", "jingzhong"]],
	xin_quancong: ["male", "wu", 4, ["sbyaoming"]],
	re_xunyu: ["male", "wei", 3, ["quhu", "rejieming"], ["clan:颍川荀氏"]],
	xin_jushou: ["male", "qun", "2/3/3", ["xinjianying", "shibei"]],
	re_bulianshi: ["female", "wu", 3, ["reanxu", "zhuiyi"]],
	re_caiwenji: ["female", "qun", 3, ["rebeige", "duanchang"]],
	sp_jianggan: ["male", "wei", 3, ["mbdaoshu", "spdaizui"]],
	peixiu: ["male", "qun", 3, ["xingtu", "juezhi"], ["border:jin"]],
	re_gaoshun: ["male", "qun", 4, ["rexianzhen", "rejinjiu"]],
	re_wuguotai: ["female", "wu", 3, ["reganlu", "buyi"], ["name:丁|null"]],
	xin_sunxiu: ["male", "wu", 3, ["mobileyanzhu", "mobilexingxue", "zhaofu"], ["zhu"]],
	sp_maojie: ["male", "wei", 3, ["bingqing", "yingfeng"]],
	re_yufan: ["male", "wu", 3, ["zhiyan", "rezongxuan"]],
	sunhanhua: ["female", "wu", 3, ["chongxu", "miaojian", "shhlianhua"]],
	yanpu: ["male", "qun", 3, ["huantu", "bihuo"]],
	mayuanyi: ["male", "qun", 4, ["jibing", "wangjing", "moucuan"]],
	fuqian: ["male", "shu", 4, ["jueyong", "poxiang"]],
	xin_caozhen: ["male", "wei", 4, ["mbsidi"]],
	xin_sunluban: ["female", "wu", 3, ["xinzenhui", "xinjiaojin"]],
	qiaozhou: ["male", "shu", 3, ["zhiming", "xingbu"]],
	xin_guyong: ["male", "wu", 3, ["xinshenxing", "xinbingyi"]],
	re_zhonghui: ["male", "wei", 4, ["requanji", "zili"], ["clan:颍川钟氏"]],
	xin_caifuren: ["female", "qun", 3, ["xinqieting", "xianzhou"], ["name:蔡|null"]],
	xin_zhoucang: ["male", "shu", 4, ["mobilezhongyong"]],
	ol_yujin: ["male", "wei", 4, ["rejieyue"], ["die:yujin_yujin.mp3"]],
	zhouqun: ["male", "shu", 3, ["tiansuan"]],
	re_zhurong: ["female", "shu", 4, ["juxiang", "relieren"], ["doublegroup:shu:qun"]],
	re_jiangwei: ["male", "shu", 4, ["retiaoxin", "zhiji"]],
	nanhualaoxian: ["male", "qun", 3, ["yufeng", "tianshu"], ["name:庄|周"]],
	re_handang: ["male", "wu", 4, ["regongji", "jiefan"]],
	re_dengai: ["male", "wei", 4, ["retuntian", "zaoxian"]],
	xin_fuhuanghou: ["female", "qun", 3, ["xinzhuikong", "xinqiuyuan"]],
	xin_panzhangmazhong: ["male", "wu", 4, ["xinduodao", "xinanjian"], ["name:潘|璋-马|忠"]],
	xin_guohuai: ["male", "wei", 4, ["mobilejingce"]],
	gongsunkang: ["male", "qun", 4, ["juliao", "taomie"], ["name:公孙|康"]],
	xin_zhangfei: ["male", "shu", 4, ["new_repaoxiao", "liyong"], ["die:re_zhangfei"]],
	xin_hansui: ["male", "qun", "4/4/1", ["xinniluan", "xiaoxi_hansui"], ["die:hansui"]],
	hucheer: ["male", "qun", 4, ["daoji"]],
	re_lingtong: ["male", "wu", 4, ["rexuanfeng"]],
	re_liubiao: ["male", "qun", 3, ["zishou", "rezongshi"]],
	simashi: ["male", "wei", 4, ["baiyi", "jinglve", "shanli"], ["name:司马|师", "border:jin"]],
	yanghuiyu: ["female", "wei", 3, ["hongyi", "requanfeng"], ["border:jin"]],
	xin_zhuran: ["male", "wu", 4, ["mobiledanshou"]],
	xin_gongsunzan: ["male", "qun", 4, ["xinyicong", "qiaomeng"], ["die:gongsunzan", "name:公孙|瓒"]],
	dingyuan: ["male", "qun", 4, ["beizhu"]],
	xin_jianyong: ["male", "shu", 3, ["xinqiaoshui", "xinjyzongshi"]],
	xin_caozhang: ["male", "wei", 4, ["rejiangchi"]],
	xin_liaohua: ["male", "shu", 4, ["redangxian", "refuli"]],
	furong: ["male", "shu", 4, ["xuewei", "liechi"]],
	re_dongzhuo: ["male", "qun", 8, ["rejiuchi", "roulin", "benghuai", "baonue"], ["zhu"]],
	re_xusheng: ["male", "wu", 4, ["repojun"]],
	sp_sufei: ["male", "qun", 4, ["zhengjian", "gaoyuan"]],
	re_sunjian: ["male", "wu", 4, ["gzyinghun", "repolu"]],
	zhengxuan: ["male", "qun", 3, ["zhengjing"]],
	dengzhi: ["male", "shu", 3, ["jimeng", "shuaiyan"]],
	xin_chengpu: ["male", "wu", 4, ["relihuo", "chunlao"]],
	yangyi: ["male", "shu", 3, ["duoduan", "gongsun"]],
	dongcheng: ["male", "qun", 4, ["chengzhao"]],
	re_pangtong: ["male", "shu", 3, ["xinlianhuan", "niepan"]],
	re_guanqiujian: ["male", "wei", 4, ["rezhengrong", "rehongju"], ["name:毌丘|俭", "die:guanqiujian"]],
	chendeng: ["male", "qun", 3, ["zhouxuan", "fengji"]],
	re_heqi: ["male", "wu", 4, ["reqizhou", "reshanxi"], ["die:heqi"]],
	yangbiao: ["male", "qun", 3, ["zhaohan", "rangjie", "yizheng"]],
	re_sp_zhugeliang: ["male", "shu", 3, ["bazhen", "rehuoji", "rekanpo"], ["name:诸葛|亮"]],
	xin_xiahoudun: ["male", "wei", 4, ["reganglie", "xinqingjian"], ["name:夏侯|惇", "die:re_xiahoudun"]],
	zhangyì: ["male", "shu", 4, ["rezhiyi"]],
	jiakui: ["male", "wei", 4, ["tongqu", "xinwanlan"]],
	re_jikang: ["male", "wei", 3, ["new_qingxian", "new_juexiang"], ["die:jikang"]],
	miheng: ["male", "qun", 3, ["kuangcai", "shejian"]],
	taoqian: ["male", "qun", 3, ["zhaohuo", "yixiang", "yirang"]],
	liuzan: ["male", "wu", 4, ["fenyin"]],
	lingcao: ["male", "wu", 4, ["dujin"]],
	sunru: ["female", "wu", 3, ["yingjian", "shixin"]],
	lifeng: ["male", "shu", 3, ["tunchu", "shuliang"]],
	zhuling: ["male", "wei", 4, ["xinzhanyi"]],
	liuye: ["male", "wei", 3, ["polu", "choulve"]],
	zhaotongzhaoguang: ["male", "shu", 4, ["yizan_use", "xinfu_longyuan"], ["name:赵|统-赵|广"]],
	majun: ["male", "wei", 3, ["xinfu_jingxie", "qiaosi"]],
	simazhao: ["male", "wei", 3, ["xinfu_daigong", "xinfu_zhaoxin"], ["name:司马|昭", "border:jin"]],
	wangyuanji: ["female", "wei", 3, ["xinfu_qianchong", "xinfu_shangjian"], ["border:jin"]],
	pangdegong: ["male", "qun", 3, ["xinfu_pingcai", "xinfu_pdgyingshi"]],
	old_yuanshu: ["male", "qun", 4, ["xinyongsi", "yjixi"], ["die:yuanshu"]],
	zhangbu: ["male", "wu", 4, ["mbchengxiong", "mbwangzhuang"]],
	mb_wangjing: ["male", "wei", 3, ["mbzujin", "mbjiejian"]],

	shenpei: ["male", "qun", "2/3", ["shouye", "liezhi"]],
	re_wangyun: ["male", "qun", 3, ["relianji", "remoucheng"], ["clan:太原王氏", "die:wangyun"]],

	re_baosanniang: ["female", "shu", 3, ["meiyong", "rexushen", "rezhennan"], ["die:baosanniang"]],

	hujinding: ["female", "shu", "2/6", ["renshi", "wuyuan", "huaizi"]],

	re_zhanggong: ["male", "wei", 3, ["reqianxin", "rezhenxing"], ["die:zhanggong"]],
	re_xugong: ["male", "qun", 3, ["rebiaozhao", "yechou"], ["doublegroup:wu:qun", "die:xugong"]],
	re_weiwenzhugezhi: ["male", "wu", 4, ["refuhai"], ["name:卫|温-诸葛|直", "die:weiwenzhugezhi"]],

	xin_yuanshao: ["male", "qun", 4, ["reluanji", "xueyi"], ["zhu"]],
	re_liushan: ["male", "shu", 3, ["xiangle", "refangquan", "ruoyu"], ["zhu"]],
	re_sunben: ["male", "wu", 4, ["jiang", "rehunzi", "zhiba"], ["zhu"]],

	scs_zhangrang: ["male", "qun", "", ["scstaoluan"], ["unseen", "sex:male_castrated"]],
	scs_zhaozhong: ["male", "qun", "", ["scschiyan"], ["unseen", "sex:male_castrated"]],
	scs_sunzhang: ["male", "qun", "", ["scszimou"], ["unseen", "sex:male_castrated"]],
	scs_bilan: ["male", "qun", "", ["scspicai"], ["unseen", "sex:male_castrated"]],
	scs_xiayun: ["male", "qun", "", ["scsyaozhuo"], ["unseen", "sex:male_castrated"]],
	scs_hankui: ["male", "qun", "", ["scsxiaolu"], ["unseen", "sex:male_castrated"]],
	scs_lisong: ["male", "qun", "", ["scskuiji"], ["unseen", "sex:male_castrated"]],
	scs_duangui: ["male", "qun", "", ["scschihe"], ["unseen", "sex:male_castrated"]],
	scs_guosheng: ["male", "qun", "", ["scsniqu"], ["unseen", "sex:male_castrated"]],
	scs_gaowang: ["male", "qun", "", ["scsmiaoyu"], ["unseen", "sex:male_castrated"]],
};

export default characters;
