const characterReplaces = {
	caochun: ["caochun", "old_caochun"],
	majun: ["majun", "yj_majun", "old_majun"],
	zhanggong: ["zhanggong", "re_zhanggong"],
	baosanniang: ["xin_baosanniang", "re_baosanniang", "baosanniang"],
	heqi: ["re_heqi", "heqi"],
	weiwenzhugezhi: ["weiwenzhugezhi", "re_weiwenzhugezhi", "jsrg_weiwenzhugezhi"],
	xugong: ["xugong", "re_xugong", "jsrg_xugong"],
	liuzan: ["re_liuzan", "liuzan", "std_liuzan"],
	yj_sufei: ["yj_sufei", "sp_sufei", "xf_sufei"],
	jiakui: ["jiakui", "old_jiakui"],
	shenpei: ["shenpei", "sp_shenpei"],
	sunru: ["dc_sunru", "ol_sunru", "sunru"],
	liuye: ["dc_liuye", "liuye", "std_liuye"],
	zhaotongzhaoguang: ["dc_zhaotongzhaoguang", "zhaotongzhaoguang"],
	yangbiao: ["yangbiao", "dc_yangbiao", "jsrg_yangbiao"],
	qiaozhou: ["yj_qiaozhou", "qiaozhou", "tw_qiaozhou"],
	sunhanhua: ["dc_sunhanhua", "sunhanhua"],
	zhoubuyi: ["zhoubuyi", "yj_zhoubuyi"],
	xianglang: ["xianglang", "mb_xianglang"],
	miheng: ["yue_miheng", "re_miheng", "miheng"],
	peixiu: ["ol_peixiu", "peixiu"],
	chendeng: ["chendeng", "re_chendeng", "ol_chendeng", "jsrg_chendeng"],
	liuba: ["liuba", "ol_liuba", "dc_liuba"],
	lingcao: ["lingcao", "dc_lingcao"],
};

export default characterReplaces;
