const characterReplaces = {
	caoren: ["caoren", "old_caoren", "sb_caoren", "new_caoren", "star_caoren"],
	sp_caoren: ["sp_caoren", "jsp_caoren"],
	xiahouyuan: ["re_xiahouyuan", "ol_xiahouyuan", "xiahouyuan"],
	huangzhong: ["re_huangzhong", "ol_huangzhong", "sb_huangzhong", "huangzhong", "jsrg_huangzhong"],
	weiyan: ["re_weiyan", "ol_weiyan", "weiyan"],
	zhoutai: ["zhoutai", "xin_zhoutai", "old_zhoutai"],
	xiaoqiao: ["xiaoqiao", "ol_xiaoqiao", "re_xiaoqiao", "sb_xiaoqiao", "old_xiaoqiao"],
	yuji: ["xin_yuji", "re_yuji", "yuji"],
	zhangjiao: ["sp_zhangjiao", "re_zhangjiao", "sb_zhangjiao", "zhangjiao"],
	dianwei: ["dianwei", "ol_dianwei", "re_dianwei"],
	xunyu: ["xunyu", "ol_xunyu", "re_xunyu", "sb_xunyu"],
	sp_zhugeliang: ["sp_zhugeliang", "ol_sp_zhugeliang", "re_sp_zhugeliang", "sb_sp_zhugeliang"],
	pangtong: ["pangtong", "ol_pangtong", "re_pangtong", "sb_pangtong"],
	re_jsp_pangtong: ["re_jsp_pangtong", "jsrg_pangtong", "sp_pangtong"],
	taishici: ["taishici", "re_taishici", "ol_sb_taishici"],
	re_yuanshao: ["re_yuanshao", "ol_yuanshao", "xin_yuanshao", "ol_sb_yuanshao", "star_yuanshao", "sb_yuanshao"],
	pangde: ["re_pangde", "ol_pangde", "pangde"],
	yanwen: ["yanwen", "ol_yanwen", "re_yanwen"],
	caopi: ["caopi", "re_caopi", "ps_caopi", "sb_caopi"],
	xuhuang: ["re_xuhuang", "ol_xuhuang", "sb_xuhuang", "xuhuang"],
	menghuo: ["menghuo", "re_menghuo", "sb_menghuo", "tw_menghuo"],
	zhurong: ["zhurong", "ol_zhurong", "re_zhurong", "sb_zhurong"],
	sunjian: ["sunjian", "ol_sunjian", "re_sunjian", "tw_ol_sunjian"],
	jiaxu: ["jiaxu", "re_jiaxu", "ns_jiaxu", "ps_jiaxu"],
	dongzhuo: ["dongzhuo", "ol_dongzhuo", "re_dongzhuo", "star_dongzhuo", "sp_dongzhuo", "yj_dongzhuo"],
	dengai: ["dengai", "ol_dengai", "re_dengai"],
	sp_ol_zhanghe: ["sp_ol_zhanghe", "yj_zhanghe", "sp_zhanghe", "jsrg_zhanghe"],
	jiangwei: ["jiangwei", "ol_jiangwei", "re_jiangwei", "ol_sb_jiangwei", "sb_jiangwei", "jsrg_jiangwei"],
	liushan: ["liushan", "ol_liushan", "re_liushan"],
	sunce: ["sunce", "re_sunce", "re_sunben", "sb_sunce", "dc_sunce"],
	zhangzhang: ["zhangzhang", "ol_zhangzhang", "re_zhangzhang"],
	zuoci: ["zuoci", "re_zuoci"],
	caiwenji: ["caiwenji", "ol_caiwenji", "re_caiwenji"],
	xuyou: ["xuyou", "sp_xuyou", "jsrg_xuyou", "yj_xuyou", "junk_xuyou"],
	guanqiujian: ["guanqiujian", "re_guanqiujian", "tw_guanqiujian", "mb_sp_guanqiujian", "old_guanqiujian"],
	chendao: ["chendao", "ns_chendao", "old_chendao"],
	zhugezhan: ["zhugezhan", "old_zhugezhan"],
	ol_lusu: ["re_lusu", "ol_lusu", "dc_sb_lusu"],
	zhanghe: ["zhanghe", "re_zhanghe", "sb_zhanghe"],
	yl_luzhi: ["yl_luzhi", "sb_yl_luzhi", "tw_yl_luzhi"],
	sunliang: ["sunliang", "xin_sunliang"],
};

export default characterReplaces;
