const characterReplaces = {
	caoren: ["caoren", "old_caoren", "sb_caoren", "new_caoren", "star_caoren"],
	sp_caoren: ["sp_caoren", "jsp_caoren", "drag_caoren"],
	xiahouyuan: ["re_xiahouyuan", "ol_xiahouyuan", "xiahouyuan"],
	huangzhong: ["re_huangzhong", "ol_huangzhong", "sb_huangzhong", "huangzhong", "jsrg_huangzhong", "yj_huangzhong", "wuhujiang", "ty_huangzhong"],
	weiyan: ["re_weiyan", "ol_weiyan", "weiyan", "huan_weiyan", "yj_weiyan"],
	zhoutai: ["zhoutai", "xin_zhoutai", "old_zhoutai"],
	xiaoqiao: ["xiaoqiao", "ol_xiaoqiao", "re_xiaoqiao", "sb_xiaoqiao", "old_xiaoqiao", "jd_sb_xiaoqiao", "yue_xiaoqiao"],
	yuji: ["xin_yuji", "re_yuji", "yuji"],
	zhangjiao: ["sp_zhangjiao", "re_zhangjiao", "sb_zhangjiao", "jsrg_zhangjiao", "zhangjiao"],
	dianwei: ["dianwei", "ol_dianwei", "re_dianwei", "dc_sb_dianwei", "xia_dianwei"],
	xunyu: ["xunyu", "ol_xunyu", "re_xunyu", "sb_xunyu", "star_xunyu"],
	sp_zhugeliang: ["sp_zhugeliang", "ol_sp_zhugeliang", "re_sp_zhugeliang", "sb_sp_zhugeliang", "jd_sb_sp_zhugeliang"],
	pangtong: ["pangtong", "ol_pangtong", "re_pangtong", "ol_sb_pangtong", "sb_pangtong", "jd_sb_pangtong"],
	re_jsp_pangtong: ["re_jsp_pangtong", "jsrg_pangtong", "sp_pangtong"],
	taishici: ["taishici", "re_taishici", "ol_sb_taishici"],
	re_yuanshao: ["re_yuanshao", "ol_yuanshao", "xin_yuanshao", "ol_sb_yuanshao", "star_yuanshao", "sb_yuanshao", "jd_sb_yuanshao", "jsrg_yuanshao", "yy_yuanshao"],
	pangde: ["re_pangde", "ol_pangde", "pangde", "sp_pangde"],
	yanwen: ["yanwen", "ol_yanwen", "re_yanwen"],
	tw_yanliang: ["tw_yanliang", "ns_yanliang"],
	tw_wenchou: ["tw_wenchou", "yy_wenchou"],
	caopi: ["caopi", "re_caopi", "ps_caopi", "sb_caopi"],
	xuhuang: ["re_xuhuang", "ol_xuhuang", "sb_xuhuang", "xuhuang", "jd_sb_xuhuang", "yj_xuhuang"],
	menghuo: ["menghuo", "re_menghuo", "sb_menghuo", "sp_menghuo", "dc_sp_menghuo", "jd_sb_menghuo"],
	zhurong: ["zhurong", "ol_zhurong", "re_zhurong", "sb_zhurong", "dc_sp_zhurong"],
	sunjian: ["sunjian", "ol_sunjian", "re_sunjian", "star_sunjian", "ol_sb_sunjian", "jsrg_sunjian"],
	jiaxu: ["jiaxu", "re_jiaxu", "ns_jiaxu", "ps_jiaxu", "dc_sb_jiaxu", "sb_jiaxu"],
	dongzhuo: ["dongzhuo", "ol_dongzhuo", "re_dongzhuo", "star_dongzhuo", "jsrg_dongzhuo", "sp_dongzhuo", "yj_dongzhuo", "new_yj_dongzhuo"],
	dengai: ["dengai", "ol_dengai", "re_dengai", "jsrg_dengai"],
	sp_ol_zhanghe: ["sp_ol_zhanghe", "yj_zhanghe", "tw_yj_zhanghe", "sp_zhanghe", "jsrg_zhanghe", "huan_zhanghe"],
	jiangwei: ["jiangwei", "ol_jiangwei", "re_jiangwei", "ol_sb_jiangwei", "sb_jiangwei", "jsrg_jiangwei", "huan_jiangwei", "jd_sb_jiangwei", "sp_jiangwei"],
	liushan: ["liushan", "ol_liushan", "re_liushan", "huan_liushan"],
	sunce: ["sunce", "re_sunce", "re_sunben", "sb_sunce", "dc_sunce", "jsrg_sunce", "sp_sunce"],
	zhangzhang: ["zhangzhang", "ol_zhangzhang", "re_zhangzhang", "tw_zhangzhao", "tw_zhanghong", "star_zhangzhao"],
	zuoci: ["zuoci", "re_zuoci"],
	caiwenji: ["caiwenji", "ol_caiwenji", "re_caiwenji", "yue_caiwenji", "sp_caiwenji"],
	xuyou: ["xuyou", "sp_xuyou", "jsrg_xuyou", "yj_xuyou", "junk_xuyou"],
	guanqiujian: ["guanqiujian", "re_guanqiujian", "tw_guanqiujian", "mb_sp_guanqiujian", "old_guanqiujian"],
	chendao: ["chendao", "ns_chendao", "old_chendao"],
	zhugezhan: ["zhugezhan", "old_zhugezhan"],
	ol_lusu: ["re_lusu", "ol_lusu", "dc_sb_lusu", "xia_lusu"],
	zhanghe: ["zhanghe", "re_zhanghe", "sb_zhanghe"],
	yl_luzhi: ["yl_luzhi", "jsrg_yl_luzhi", "sb_yl_luzhi", "tw_yl_luzhi"],
	sunliang: ["sunliang", "xin_sunliang"],
	zhoufei: ["zhoufei", "yue_zhoufei"],
	lukang: ["lukang", "jsrg_lukang"],
};

export default characterReplaces;
