const characters = {
	re_huangzhong: ["male", "shu", 4, ["xinliegong"]],
	old_zhoutai: ["male", "wu", 4, ["gzbuqu"]],
	old_caoren: ["male", "wei", 4, ["jushou"], ["die:new_caoren"]],
	re_xuhuang: ["male", "wei", 4, ["duanliang", "jiezi"]],
	re_pangde: ["male", "qun", 4, ["mashu", "jianchu"]],
	re_xiahouyuan: ["male", "wei", 4, ["xinshensu"], ["name:夏侯|渊"]],
	re_weiyan: ["male", "shu", 4, ["xinkuanggu", "qimou"]],
	xiaoqiao: ["female", "wu", 3, ["retianxiang", "hongyan"], ["name:桥|null"]],
	sp_zhangjiao: ["male", "qun", 3, ["releiji", "guidao", "huangtian"], ["zhu"]],
	re_yuji: ["male", "qun", 3, ["xinfu_guhuo"]],
	// yuji:['male','qun',3,['guhuo']],
	// xin_yuji:['male','qun',3,['guhuo']],

	sp_zhugeliang: ["male", "shu", 3, ["bazhen", "huoji", "kanpo"], ["name:诸葛|亮"]],
	pangtong: ["male", "shu", 3, ["lianhuan", "oldniepan"]],
	xunyu: ["male", "wei", 3, ["quhu", "jieming"], ["clan:颍川荀氏"]],
	dianwei: ["male", "wei", 4, ["qiangxix"]],
	taishici: ["male", "wu", 4, ["tianyi"], ["name:太史|慈"]],
	yanwen: ["male", "qun", 4, ["shuangxiong"], ["name:颜|良-文|丑"]],
	re_yuanshao: ["male", "qun", 4, ["luanji", "xueyi"], ["zhu", "die:yuanshao"]],

	menghuo: ["male", "shu", 4, ["huoshou", "zaiqixx", "twqiushou"], ["zhu", "doublegroup:shu:qun"]],
	zhurong: ["female", "shu", 4, ["juxiang", "lieren"], ["doublegroup:shu:qun"]],
	caopi: ["male", "wei", 3, ["xingshang", "fangzhu", "songwei"], ["zhu"]],
	re_lusu: ["male", "wu", 3, ["haoshi", "dimeng"]],
	sunjian: ["male", "wu", 4, ["gzyinghun"]],
	dongzhuo: ["male", "qun", 8, ["jiuchi", "roulin", "benghuai", "baonue"], ["zhu"]],
	jiaxu: ["male", "qun", 3, ["luanwu", "wansha", "weimu"]],

	jiangwei: ["male", "shu", 4, ["tiaoxin", "zhiji"]],
	liushan: ["male", "shu", 3, ["xiangle", "fangquan", "ruoyu"], ["zhu"]],
	zhanghe: ["male", "wei", 4, ["qiaobian"]],
	dengai: ["male", "wei", 4, ["tuntian", "zaoxian"]],
	sunce: ["male", "wu", 4, ["jiang", "hunzi", "zhiba"], ["zhu"]],
	zhangzhang: ["male", "wu", 3, ["zhijian", "guzheng"], ["name:张|昭-张|纮"]],
	caiwenji: ["female", "qun", 3, ["beige", "duanchang"]],
	zuoci: ["male", "qun", 3, ["huashen", "xinsheng"]],

	wangji: ["male", "wei", 3, ["qizhi", "jinqu"]],
	yanyan: ["male", "shu", 4, ["nzry_juzhan"], []],
	wangping: ["male", "shu", 4, ["nzry_feijun", "nzry_binglve"], []],
	luji: ["male", "wu", 3, ["nzry_huaiju", "nzry_yili", "nzry_zhenglun"], []],
	sunliang: ["male", "wu", 3, ["nzry_kuizhu", "nzry_zhizheng", "nzry_lijun"], ["zhu"]],
	xuyou: ["male", "qun", 3, ["nzry_chenglve", "nzry_shicai", "nzry_cunmu"]],
	yl_luzhi: ["male", "qun", 3, ["nzry_mingren", "nzry_zhenliang"], []],
	kuailiangkuaiyue: ["male", "wei", 3, ["nzry_jianxiang", "nzry_shenshi"], ["name:蒯|良-蒯|越"]],

	guanqiujian: ["male", "wei", 4, ["zhengrong", "hongju"], ["name:毌丘|俭"]],
	haozhao: ["male", "wei", 4, ["drlt_zhenggu"], []],
	zhugezhan: ["male", "shu", 3, ["xinfu_zuilun", "xinfu_fuyin"], ["name:诸葛|瞻"]],
	lukang: ["male", "wu", 4, ["drlt_qianjie", "drlt_jueyan", "drlt_poshi"], []],
	yl_yuanshu: ["male", "qun", 4, ["drlt_yongsi", "drlt_weidi"], ["zhu"]],
	zhangxiu: ["male", "qun", 4, ["drlt_xiongluan", "drlt_congjian", "twjuxiang"], ["zhu"]],
	chendao: ["male", "shu", 4, ["dcwanglie"], []],
	zhoufei: ["female", "wu", 3, ["olliangyin", "olkongsheng"], ["name:周|null"]],
};

export default characters;
